import React, { useCallback, useEffect, useRef, useState } from "react";
import { Box, IconButton, Stack, Tooltip } from "@mui/material";
import Insets from "./bodyMaps/InsetSvgs";
import MouseBodyMap from "./bodyMaps/mouse/MouseBodyMap";
import { MouseCellsList } from "./bodyMaps/mouse/mouseMapping";
import UnfoldLessIcon from "@mui/icons-material/UnfoldLess";
import UnfoldMoreIcon from "@mui/icons-material/UnfoldMore";
import { BiosampleTable, EncodeBiosample } from "@weng-lab/ui-components";
import {
  GridEventListener,
  GridGroupNode,
  GridRowClassNameParams,
  GridRowParams,
  gridRowNodeSelector,
  isAutogeneratedRow,
  useGridApiRef,
} from "@mui/x-data-grid-premium";

export default function Mouse() {
  const [selected, setSelected] = useState<string | null>(null);
  const [showBodyMap, setShowBodyMap] = useState<boolean>(true);
  const apiRef = useGridApiRef();
  const previousSelectedRef = useRef<string | null>(null);
  const hoveredRef = useRef<string | null>(null);
  const mapContainerRef = useRef<HTMLDivElement | null>(null);
  const tableContainerRef = useRef<HTMLDivElement | null>(null);

  const getRowNode = useCallback((rowId: string | number) => gridRowNodeSelector(apiRef, rowId), [apiRef]);

  const getOrgan = (params: GridRowParams<EncodeBiosample>) => {
    const rowNode = getRowNode(params.id);

    if (rowNode?.type === "group" && rowNode.groupingField === "ontology" && typeof rowNode.groupingKey === "string") {
      return rowNode.groupingKey;
    }

    if (!isAutogeneratedRow(params.row) && typeof params.row.ontology === "string") {
      return params.row.ontology;
    }

    return null;
  };

  const handleRowClick: GridEventListener<"rowClick"> = (params) => {
    const organ = getOrgan(params);
    if (!organ) return;

    const rowNode = getRowNode(params.id);
    if (rowNode?.type === "group") {
      setSelected((prev) => (prev === organ ? null : organ));
      return;
    }

    // setSelected(organ);
  };

  const getOntologyGroupId = useCallback(
    (organ: string | null) => {
      if (!organ) return null;

      const candidateRowIds = [
        ...apiRef.current.getSortedRowIds(),
        ...Object.keys((apiRef.current.state as { rows?: { tree?: Record<string, unknown> } }).rows?.tree ?? {}),
      ];

      for (const rowId of candidateRowIds) {
        const rowNode = getRowNode(rowId);
        if (
          rowNode?.type === "group" &&
          rowNode.groupingField === "ontology" &&
          typeof rowNode.groupingKey === "string" &&
          rowNode.groupingKey === organ
        ) {
          return rowId;
        }
      }

      return null;
    },
    [apiRef, getRowNode]
  );

  const getRowClassName = (params: GridRowClassNameParams<EncodeBiosample>) => {
    const organ = getOrgan(params);
    if (!organ) return "";

    return ["biosample-row", organ === selected ? "biosample-row-selected" : ""].filter(Boolean).join(" ");
  };

  const setMapHoverClass = (organ: string | null, active: boolean) => {
    if (!organ || !mapContainerRef.current) return;

    const elements = Array.from(
      mapContainerRef.current.querySelectorAll<HTMLElement | SVGElement>("[data-organ]")
    ).filter((element) => element.getAttribute("data-organ") === organ);

    elements.forEach((element) => element.classList.toggle("biosample-hovered", active));
  };

  const setTableHoverClass = (organ: string | null, active: boolean) => {
    if (!organ || !tableContainerRef.current) return;

    const groupId = getOntologyGroupId(organ);
    if (!groupId) return;

    const rowElement = tableContainerRef.current.querySelector<HTMLElement>(`[data-id="${String(groupId)}"]`);
    rowElement?.classList.toggle("biosample-row-hovered", active);
  };

  const setHoveredOrgan = (organ: string | null) => {
    if (hoveredRef.current === organ) return;

    setMapHoverClass(hoveredRef.current, false);
    setTableHoverClass(hoveredRef.current, false);

    hoveredRef.current = organ;

    setMapHoverClass(organ, true);
    setTableHoverClass(organ, true);
  };

  useEffect(() => {
    const previousSelected = previousSelectedRef.current;

    if (previousSelected && previousSelected !== selected) {
      const previousGroupId = getOntologyGroupId(previousSelected);
      if (previousGroupId) {
        apiRef.current.setRowChildrenExpansion(previousGroupId, false);
      }
    }

    if (!selected) {
      previousSelectedRef.current = selected;
      return;
    }

    const selectedGroupId = getOntologyGroupId(selected);
    if (!selectedGroupId) {
      previousSelectedRef.current = selected;
      return;
    }

    apiRef.current.setRowChildrenExpansion(selectedGroupId, true);

    requestAnimationFrame(() => {
      const rowIndex = apiRef.current.getRowIndexRelativeToVisibleRows(selectedGroupId);
      if (rowIndex >= 0) {
        apiRef.current.scrollToIndexes({ rowIndex });
      }
    });

    previousSelectedRef.current = selected;
  }, [apiRef, getOntologyGroupId, selected]);

  const handleRowExpansionChange = (groupNode: GridGroupNode) => {
    if (groupNode.groupingField !== "ontology" || typeof groupNode.groupingKey !== "string") {
      return;
    }

    const organ = groupNode.groupingKey;

    setSelected((prev) => {
      if (groupNode.childrenExpanded) {
        return organ;
      }

      return prev === organ ? null : prev;
    });
  };

  return (
    <Stack
      direction={{ xs: "column", md: "row" }}
      spacing={4}
      mt={2}
      sx={{
        position: "relative",
        overflow: "hidden",
        alignItems: "stretch",
      }}
      px={1}
    >
      <Tooltip title={showBodyMap ? "Hide Body Map" : "Show Body Map"} placement="bottom">
        <IconButton
          onClick={() => setShowBodyMap((prev) => !prev)}
          sx={{
            position: "absolute",
            top: 10,
            alignSelf: "flex-start",
            zIndex: 2,
            backgroundColor: "background.paper",
            boxShadow: 2,
            "&:hover": { backgroundColor: "action.hover" },
          }}
        >
          {showBodyMap ? (
            <UnfoldLessIcon sx={{ transform: { sx: "none)", md: "rotate(90deg)" } }} />
          ) : (
            <UnfoldMoreIcon sx={{ transform: { sx: "none", md: "rotate(90deg)" } }} />
          )}
        </IconButton>
      </Tooltip>
      <Box
        sx={{
          width: {
            xs: "100%",
            md: showBodyMap ? 550 : 0,
          },
          height: {
            xs: showBodyMap ? "auto" : 0,
            md: "auto",
          },
          minWidth: 0,
          transition: {
            xs: "height 0.5s ease",
            md: "width 0.6s ease",
          },
          overflow: "hidden",
          position: "relative",
        }}
      >
        <Stack
          ref={mapContainerRef}
          sx={{
            opacity: showBodyMap ? 1 : 0,
            transition: "opacity 0.4s ease",
            "& .biosample-map-organ": {
              transition: "fill 0.2s ease, stroke 0.2s ease, opacity 0.2s ease",
            },
            "& .biosample-map-organ.biosample-hovered": {
              fill: "#63326e79 !important",
              stroke: "#63326eff !important",
            },
            "& .biosample-inset-button.biosample-hovered .biosample-inset-overlay": {
              backgroundColor: "rgba(128, 90, 213, 0.25)",
            },
          }}
        >
          <MouseBodyMap selected={selected} setSelected={setSelected} onHoverChange={setHoveredOrgan} />
          <Insets
            Assembly="mm10"
            cellsList={MouseCellsList}
            selected={selected}
            setSelected={setSelected}
            onHoverChange={setHoveredOrgan}
          />
        </Stack>
      </Box>
      <Box
        ref={tableContainerRef}
        sx={{
          flexGrow: 1,
          transition: {
            xs: "height 0.5s ease",
            md: "all 0.6s ease",
          },
          width: {
            xs: "100%",
            md: showBodyMap ? "calc(100% - 550px)" : "100%",
          },
          height: {
            xs: showBodyMap ? "auto" : "100%",
            md: "auto",
          },
        }}
      >
        <BiosampleTable
          apiRef={apiRef}
          label={"Select a Biosample"}
          assembly={"mm10"}
          disableMultipleRowSelection
          isRowSelectable={(params) => !isAutogeneratedRow(params.row)}
          disableRowSelectionOnClick={false}
          divHeight={{ height: 700, maxHeight: 700 }}
          getRowClassName={getRowClassName}
          onRowClick={handleRowClick}
          onReady={(gridApiRef) => [
            gridApiRef.current.subscribeEvent("rowMouseEnter", (params) => setHoveredOrgan(getOrgan(params))),
            gridApiRef.current.subscribeEvent("rowMouseLeave", () => setHoveredOrgan(null)),
            gridApiRef.current.subscribeEvent("rowExpansionChange", handleRowExpansionChange),
          ]}
          sx={{
            "& .biosample-row": { cursor: "pointer" },
            "& .biosample-row-hovered": { backgroundColor: "action.hover" },
            "& .biosample-row-selected": { backgroundColor: "action.selected" },
          }}
          disableRowGrouping={false}
        />
      </Box>
    </Stack>
  );
}
