"use client";
import React from "react";
import {
  Box,
  Divider,
  Link,
  List,
  ListItem,
  Paper,
  Stack,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Typography,
} from "@mui/material";
import Grid from "@mui/material/Grid";
import Image from "next/image";
import EncyclopediaAll from "../../../public/assets/about/images/EncyclopediaAll.png";
import { CA_CTCF, CA_H3K4me3, CA_TF, CA_only, PLS, TF_only, dELS } from "../../common/colors";
import ContactForm from "./contactForm";
import { LinkComponent } from "common/components/LinkComponent";
import classifications from "../../../public/assets/about/images/classifications.png";

export default function About() {
  return (
    <main>
      <Grid
        container
        spacing={3}
        sx={{ maxWidth: "min(70%, 1000px)", minWidth: "600px", marginX: "auto", marginY: "3rem" }}
      >
        {/* Header */}
        <Grid size={12}>
          <Typography variant="h2" fontWeight={500}>
            About SCREEN
          </Typography>
          <Divider />
          <Typography mt={1} variant="body1" paragraph>
            <b>SCREEN (Search Candidate Regulatory Elements by ENCODE)</b> is a web-based visualization and discovery
            platform for exploring the ENCODE Registry of cis-Regulatory Elements (cCREs) and other ENCODE Encyclopedia
            annotations. SCREEN enables users to query, visualize, and download regulatory annotations across hundreds
            of human and mouse cell and tissue types and to examine their relationships to genes, transcription factor
            binding, chromatin state, and three-dimensional genome organization.
          </Typography>
        </Grid>
        {/* Encode Encyclopedia */}
        <Grid container size={12}>
          <Grid
            size={{
              xs: 12,
              lg: 6,
            }}
            paddingRight={6}
          >
            <Typography variant="h5" fontWeight={600}>
              The ENCODE Encyclopedia
            </Typography>
            <Typography variant="body1" paragraph>
              The ENCODE Encyclopedia is an integrated collection of functional genomic annotations derived from
              large-scale experimental data generated by the ENCODE Project. These annotations span multiple conceptual
              layers, including DNA sequence features, regulatory elements, genes and transcripts, and chromatin
              interactions. Some annotations derive directly from primary experimental data, while others reflect
              integrative analyses that combine multiple assays to provide higher-level functional interpretations.
            </Typography>
            <Typography variant="body1" paragraph>
              SCREEN provides an interactive interface for navigating these annotations, centering many views on cCREs
              as a unifying framework for regulatory analysis.
            </Typography>
          </Grid>
          <Grid
            size={{
              xs: 12,
              lg: 4,
            }}
          >
            <Image src={EncyclopediaAll} alt={"Encode Encyclopedia"} style={{ width: "100%", height: "auto" }} />
          </Grid>
        </Grid>
        {/* Reistry of cCREs */}
        <Grid container size={12}>
          <Grid size={12}>
            <Typography variant="h5" fontWeight={600}>
              The Registry of Candidate cis-Regulatory Elements (cCREs)
            </Typography>
            <Typography variant="body1" paragraph>
              The Registry of cCREs is a genome-wide catalog of candidate regulatory elements defined using chromatin
              accessibility, histone modification, and transcription factor binding data generated by ENCODE. The
              Registry is designed to be comprehensive, cell type–agnostic, and extensible as new data become available
            </Typography>
            <Typography variant="h6">
              <b>Element Anchors</b>
            </Typography>
            <Typography variant="body1" paragraph>
              In ENCODE4, cCREs are anchored using multiple complementary strategies to capture a broad spectrum of
              regulatory elements:
            </Typography>
            <List
              component="ul"
              sx={{
                listStyleType: "disc",
                paddingLeft: 4,
              }}
            >
              <ListItem component="li" sx={{ display: "list-item", whiteSpace: "normal" }}>
                <b>Representative DNase hypersensitive sites (rDHSs)</b>, generated by clustering DNase-seq peaks across
                large numbers of biosamples, define the majority of accessible regulatory regions.
              </ListItem>
              <ListItem component="li" sx={{ display: "list-item", whiteSpace: "normal" }}>
                <b>Transcription factor clusters</b>, representing reproducible transcription factor binding sites that
                do not overlap DNase hypersensitive regions, capture regulatory elements with low chromatin
                accessibility but strong, protein-binding signatures.
              </ListItem>
              <ListItem component="li" sx={{ display: "list-item", whiteSpace: "normal" }}>
                <b>Multi-mapper rDHSs</b>, derived from alignments that retain multi-mapping reads, recover regulatory
                elements in recently duplicated or repetitive genomic regions that were underrepresented in earlier
                Registry versions.
              </ListItem>
            </List>
            <Typography variant="body1" paragraph>
              Together, these anchors define millions of candidate regulatory elements in the human and mouse genomes.
            </Typography>
            <Typography variant="h6">
              <b>Quantifying Epigenomic Signals</b>
            </Typography>
            <Typography variant="body1" paragraph>
              For each cCRE anchor, we compute standardized signal summaries for chromatin accessibility (DNase-seq or
              ATAC-seq), histone modifications (H3K4me3 and H3K27ac), and CTCF binding across all available biosamples.
              Signals are converted to Z-scores within each biosample to ensure comparability across assays and
              experiments. These standardized signals form the basis for both classification and biosample-specific
              activity annotations.
            </Typography>
            <Typography variant="body1" paragraph>
              cCREs defined using multi-mapping–inclusive chromatin accessibility data do not have associated epigenomic
              signal tracks, as the full set of ENCODE assays was not reprocessed using multi-mapping–inclusive
              alignments. These elements are therefore included in the Registry as candidate regulatory elements but
              lack quantitative signal annotations.
            </Typography>
            <Typography variant="h6" id="classifications">
              <b>Cell Type–Agnostic Classification of cCREs</b>
            </Typography>
            <Typography variant="body1" paragraph>
              Each cCRE is assigned a cell type–agnostic class based on its dominant biochemical signatures across all
              surveyed biosamples and its proximity to annotated transcription start sites (TSSs). This classification
              is intended to be analogous to gene catalogs, which define genes independently of their expression levels
              in individual cell types.
            </Typography>
            <Image src={classifications} alt="Classification of cCREs" style={{ width: "100%", height: "auto" }} />
            <Typography variant="body1" paragraph>
              The major cCRE classes include:
            </Typography>
            <Stack direction={"column"} spacing={1} mt={1} mb={3}>
              <Typography paddingLeft={"1rem"} borderLeft={`0.25rem solid ${PLS}`} variant="body1">
                <b>Promoter-like</b> cCREs: Elements located near annotated or experimentally derived TSSs with high
                chromatin accessibility and H3K4me3 signal.
              </Typography>
              <Typography paddingLeft={"1rem"} borderLeft={`0.25rem solid ${dELS}`} variant="body1">
                <b>Enhancer-like</b> cCREs: Accessible elements with high H3K27ac signal, subdivided into TSS-proximal
                and TSS-distal enhancers based on distance to the nearest TSS.
              </Typography>
              <Typography paddingLeft={"1rem"} borderLeft={`0.25rem solid ${CA_H3K4me3}`} variant="body1">
                <b>Chromatin accessibility + H3K4me3 (CA–H3K4me3)</b> cCREs: Accessible elements with H3K4me3 but
                lacking strong H3K27ac and located away from TSSs.
              </Typography>
              <Typography paddingLeft={"1rem"} borderLeft={`0.25rem solid ${CA_CTCF}`} variant="body1">
                <b>Chromatin accessibility + CTCF (CA–CTCF)</b> cCREs: Accessible elements with strong CTCF binding and
                low histone acetylation.
              </Typography>
              <Typography paddingLeft={"1rem"} borderLeft={`0.25rem solid ${CA_TF}`} variant="body1">
                <b>Chromatin accessibility + transcription factor (CA–TF)</b> cCREs: Accessible elements overlapping
                transcription factor clusters but lacking strong histone modification signals.ster.
              </Typography>
              <Typography paddingLeft={"1rem"} borderLeft={`0.25rem solid ${CA_only}`} variant="body1">
                <b>Chromatin accessibility (CA)</b> cCREs: Accessible elements lacking strong H3K4me3, H3K27ac, or CTCF
                signals.
              </Typography>
              <Typography paddingLeft={"1rem"} borderLeft={`0.25rem solid ${TF_only}`} variant="body1">
                <b>Transcription factor (TF)</b> cCREs: Elements defined by transcription factor binding in the absence
                of detectable chromatin accessibility or histone modification signals.
              </Typography>
            </Stack>
            <Typography variant="body1" paragraph>
              All signal values used for classification are retained and made available in SCREEN to support custom
              filtering and user-defined analyses.
            </Typography>
          </Grid>
        </Grid>
        <Typography variant="h6" id="classifications">
          <b>Biosample-Specific Activity Annotations</b>
        </Typography>
        <Typography variant="body1" paragraph>
          In addition to cell type–agnostic classes, SCREEN annotates the <b>biosample-specific activity</b> of each
          cCRE using the corresponding epigenomic data from individual biosamples. In this context, cCREs may be
          annotated as active promoters, enhancers, or other classes in some biosamples and inactive in others,
          reflecting cell type–specific regulatory programs.
        </Typography>
        <Typography variant="body1" paragraph>
          Elements lacking sufficient chromatin accessibility signal in a given biosample are labeled as having low
          chromatin accessibility in that context.
        </Typography>
        <Grid container size={12}>
          <Grid size={12}>
            <Typography variant="h5" fontWeight={600}>
              Core, Partial, and Ancillary Collections
            </Typography>
            <Typography variant="body1" paragraph>
              Because the availability of epigenomic assays varies across biosamples, SCREEN organizes
              biosample-specific annotations into three collections:
            </Typography>
            <List
              component="ul"
              sx={{
                listStyleType: "disc",
                paddingLeft: 4,
              }}
            >
              <ListItem component="li" sx={{ display: "list-item", whiteSpace: "normal" }}>
                <b>Core Collection</b>: Biosamples with chromatin accessibility, H3K4me3, H3K27ac, and CTCF data. These
                provide the most complete and highest-confidence cCRE annotations and are recommended for most analyses.
              </ListItem>
              <ListItem component="li" sx={{ display: "list-item", whiteSpace: "normal" }}>
                <b>Partial Data Collection</b>: Biosamples with chromatin accessibility and a subset of additional
                marks. These samples enable high-resolution boundary definition but support a reduced set of cCRE
                classes.
              </ListItem>
              <ListItem component="li" sx={{ display: "list-item", whiteSpace: "normal" }}>
                <b>Ancillary Collection</b>: Biosamples lacking chromatin accessibility data. In these cases, cCREs are
                annotated only by the presence or absence of high signal for available assays, and users are advised to
                anchor analyses on cCREs defined in the Core or Partial collections.
              </ListItem>
            </List>
            <Typography variant="body1" paragraph>
              SCREEN clearly labels biosamples by collection to guide appropriate interpretation.
            </Typography>
            {/* <Image
              src={biosamples}
              style={{ display: "block", maxWidth: "600px", height: "auto", margin: "auto" }}
              alt="Biosample types visual diagram"
            /> */}
          </Grid>
          <Grid container size={12}>
            <Grid size={12}>
              <Typography variant="h5" fontWeight={600}>
                Integration with Other ENCODE Annotations
              </Typography>
              <Typography variant="body1" paragraph>
                SCREEN integrates cCREs with a wide range of additional ENCODE Encyclopedia annotations. For each cCRE,
                users can explore overlapping transcription factor binding sites, histone modification peaks, chromatin
                state segmentations, transcription start sites, three-dimensional chromatin interactions, and gene
                expression measurements. These integrations support multi-layered analyses of regulatory mechanisms.
              </Typography>
            </Grid>
            <Grid size={12} id="citations">
              <Typography variant="h5" fontWeight={600}>
                Citation and Legacy Resources
              </Typography>
              <Typography variant="body1" paragraph>
                When using cCRE annotations or analyses derived from SCREEN in publications, preprints, or other public
                disclosures, users should cite the appropriate corresponding publication. SCREEN provides access to and
                visualization of these data, but the underlying cCRE definitions, classifications, and annotations are
                described in the corresponding ENCODE cCRE manuscript and should be cited to ensure appropriate
                attribution.
              </Typography>
              <Typography variant="body1" paragraph>
                Earlier versions of SCREEN remain available for reference and reproducibility but are no longer actively
                updated. Users should be aware that data, annotations, and features in legacy versions may differ from
                the current release.
              </Typography>
              <Typography variant="body1" paragraph>
                <b>Current Version:</b>
              </Typography>
              <List
                component="ul"
                sx={{
                  listStyleType: "disc",
                  paddingLeft: 4,
                }}
              >
                <ListItem component="li" sx={{ display: "list-item", whiteSpace: "normal" }}>
                  Registry of cCREs: Version 4
                </ListItem>
                <ListItem component="li" sx={{ display: "list-item", whiteSpace: "normal" }}>
                  SCREEN UI: 2026
                </ListItem>
              </List>
              <Typography variant="body1" paragraph>
                Citation:{" "}
                <u>
                  <Link
                    href="https://www.nature.com/articles/s41586-025-09909-9"
                    target="_blank"
                    rel="noopener"
                    style={{ color: "inherit", textDecoration: "underline" }}
                  >
                    An Expanded Registry of Candidate cis-Regulatory Elements
                  </Link>
                </u>
                . Moore, J.E., Pratt, H.E., Fan, K., Phalke, N., Fisher, J., Elhajjajy, S.I., Andrews, G., Gao, M.,
                Shedd, N., Fu, Y., Lacadie, M.C., Meza, J., Khandpekar, M., Ganna, M., Choudhury, E., Swofford, R.,
                Phan, H., Ramirez, C., Campbell, M., Likhite, M., Farrell, N.P., Weimer, A.K., Pampari, A., Ramalingam,
                V., Reese, F., Borsari, B., Yu, M., Wattenberg, E., Ruiz-Romero, M., Razavi-Mohseni, M., Xu, J., Galeev,
                T., Colubri, A., Beer, M.A., Guigó, R., Gerstein, M., Engreitz, J., Ljungman, M., Reddy, T.E., Snyder,
                M.P., Epstein, C.B., Gaskell, E., Bernstein, B.E., Dickel, D.E., Visel, A., Pennacchio, L.A., Mortazavi,
                A., Kundaje, A., Weng, Z. (2026) <i>Nature</i>
              </Typography>
            </Grid>
            <Grid size={12} id="versions">
              <Typography variant="body1" paragraph>
                <b>Legacy versions:</b>
              </Typography>
              <TableContainer component={Paper}>
                <Table
                  sx={{
                    borderCollapse: "collapse",
                    "& td, & th": {
                      border: "1px solid rgba(0,0,0,0.3)",
                    },
                  }}
                >
                  <TableHead>
                    <TableRow>
                      <TableCell>
                        <b>Registry of cCREs Version</b>
                      </TableCell>
                      <TableCell>
                        <b>UI Version</b>
                      </TableCell>
                      <TableCell>
                        <b>URL</b>
                      </TableCell>
                      <TableCell>
                        <b>Citation</b>
                      </TableCell>
                    </TableRow>
                  </TableHead>
                  <TableBody>
                    <TableRow>
                      <TableCell>V4</TableCell>
                      <TableCell>2024</TableCell>
                      <TableCell>
                        <Link href="https://screen-v4.wenglab.org/" target="_blank" rel="noopener">
                          screen-v4.wenglab.org
                        </Link>
                      </TableCell>
                      <TableCell rowSpan={2}>
                        Moore…Weng (2026)
                        <br />
                        <i>Nature</i>
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>V3</TableCell>
                      <TableCell>2020</TableCell>
                      <TableCell>
                        <Link href="https://screen-v3.wenglab.org/" target="_blank" rel="noopener">
                          screen-v3.wenglab.org
                        </Link>
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>V2</TableCell>
                      <TableCell>2020</TableCell>
                      <TableCell>
                        <Link href="https://screen-v2.wenglab.org/" target="_blank" rel="noopener">
                          screen-v2.wenglab.org
                        </Link>
                      </TableCell>
                      <TableCell rowSpan={2}>
                        The ENCODE Project Consortium,
                        <br />
                        Moore…Weng (2020)
                        <br />
                        <i>Nature</i>
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>V1 (hg19)</TableCell>
                      <TableCell>2018</TableCell>
                      <TableCell>
                        <Link href="https://screen-v10.wenglab.org/" target="_blank" rel="noopener">
                          screen-v10.wenglab.org
                        </Link>
                      </TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </TableContainer>
            </Grid>
          </Grid>
          {/* API Documentation */}
          <Grid id="api-documentation" size={12}>
            <Typography variant="h5" fontWeight={600}>
              API Documentation
            </Typography>
            <LinkComponent href={"https://weng-lab.github.io/SCREEN2.0/"} showExternalIcon openInNewTab>
              SCREEN API Documentation
            </LinkComponent>
          </Grid>
          {/* Contact Us */}
          <Grid id="contact-us" size={12}>
            <Typography variant="h5" fontWeight={600}>
              Contact Us
            </Typography>
            <Typography mb={1} variant="body1">
              Send us a message and we&apos;ll be in touch!
            </Typography>
            <Typography mb={1} variant="body1">
              As this is a beta site, we would greatly appreciate any feedback you may have. Knowing how our users are
              using the site and documenting issues they may have are important to make this resource better and easier
              to use.
            </Typography>
            <Box mb={1}>
              <Typography display={"inline"} variant="body1">
                If you&apos;re experiencing an error/bug, feel free to&nbsp;
              </Typography>
              <Link
                display={"inline"}
                href="https://github.com/weng-lab/SCREEN2.0/issues"
                target="_blank"
                rel="noopener noreferrer"
              >
                submit an issue on Github.
              </Link>
            </Box>
            <Box mb={2}>
              <Typography display={"inline"} variant="body1">
                If you would like to send an attachment, feel free to email us directly at&nbsp;
              </Typography>
              <Link
                display={"inline"}
                href="mailto:encode-screen@googlegroups.com"
                target="_blank"
                rel="noopener noreferrer"
              >
                encode&#8209;screen@googlegroups.com
              </Link>
            </Box>
            <ContactForm />
          </Grid>
        </Grid>
      </Grid>
    </main>
  );
}
