export const MouseList = {
  "adrenal gland": ["cls-27"],
  "arterial blood vessel": ["cls-26"],
  "bone element": ["cls-bone", "cls-5", "cls-bone1", "cls-bone6"],
  brain: ["cls-21", "cls-22", "cls-23", "cls-24"],
  breast: ["cls-41", "cls-42"],
  colon: ["cls-colon", "cls-9"],
  esophagus: ["cls-esophagus", "cls-esophagus2", "cls-29"],
  "extraembryonic component": ["placenta"],
  eye: ["cls-39", "cls-40", "cls-eye"],
  gonad: ["testis", "ovary"],
  heart: ["cls-33", "cls-34", "cls-18"],
  intestine: [
    "cls-largeintestine",
    "cls-19",
    "cls-8",
    "cls-smallintestine",
    "cls-smallintestine19",
    "cls-colon",
    "cls-9",
  ],
  kidney: ["cls-kidney"],
  "large intestine": ["cls-largeintestine", "cls-19"],
  limb: ["cls-limb1", "cls-limb2"],
  liver: ["cls-17", "cls-liver"],
  lung: ["cls-lung"],
  "lymph node": ["cls-28"],
  "mammary gland": ["breast"],
  muscle: ["cls-14", "cls-15", "cls-16"],
  nose: ["cls-11"],
  ovary: ["cls-6", "cls-7", "cls-35"],
  pancreas: ["cls-12"],
  skin: ["cls-1", "cls-2", "cls-32", "cls-3", "cls-10"],
  "small intestine": ["cls-8", "cls-smallintestine", "cls-smallintestine19"],
  "spinal cord": ["cls-20"],
  spleen: ["cls-13"],
  stomach: ["cls-stomach"],
  testis: ["cls-37", "cls-36"],
  thymus: ["cls-30", "cls-31"],
  "urinary bladder": ["cls-38"],
  vein: ["cls-25"],
};

export const MouseCellsList = {
  adipose: [],
  blood: [],
  "bone marrow": [],
  "connective tissue": [],
  embryo: [],
  epithelium: [],
  placenta: [],
};

export const MouseColorMap: Record<
  string,
  {
    fill?: string;
    activeFill?: string;
    stroke?: string;
    activeStroke?: string;
    outlineOnly?: boolean;
    opacity?: number;
    disabled?: boolean;
  }
> = {
  "cls-1": { fill: "#b7c9d8", stroke: "#f9fcff", activeFill: "#f7e1d4", activeStroke: "#ebd7ca", disabled: true },
  "cls-bone1": { fill: "#fff", activeStroke: "#f7e1d4", stroke: "#467fb0", disabled: true },
  "cls-bone": { fill: "#fff", activeStroke: "#f7e1d4", stroke: "#467fb0", disabled: true },
  "cls-limb1": { fill: "#b7c9d8", activeFill: "#f7e1d4" },
  "cls-limb2": { fill: "#d8e2ea", activeFill: "#ccbdb4" },
  "cls-mousebody": { fill: "#d8e2ea", stroke: "#85a2b9", activeStroke: "none" },
  "cls-2": { fill: "#d8e2ea", stroke: "#85a2b9", activeFill: "#ccbdb4", activeStroke: "none", disabled: true },
  "cls-3": { fill: "#86abcb", activeFill: "#938e8c", disabled: true },
  "cls-4": { fill: "#fff", activeFill: "#fff" },
  "cls-5": { fill: "#fff", stroke: "#f9fcff", activeFill: "#fff", activeStroke: "#ebd7ca", disabled: true },
  "cls-6": { fill: "#8aa9cc", stroke: "#ecf2f7", activeFill: "#f49fcc", activeStroke: "#f5f5f5" },
  "cls-7": { fill: "#ecf2f7", stroke: "#ecf2f7", activeFill: "#f49fcc", activeStroke: "#f5f5f5" },
  "cls-8": { fill: "#a8c2d9", stroke: "#dde6ec", activeFill: "#fc927e", activeStroke: "#fcaea0" },
  "cls-9": { fill: "#dde6ec", activeFill: "#ffd6c6", activeStroke: "#fdbeb2" },
  "cls-10": { stroke: "#f9fcff", activeStroke: "#ebd7ca", disabled: true },
  "cls-11": { fill: "#3b77aa", activeFill: "#a01d58", disabled: true },
  "cls-12": { fill: "#7893ab", stroke: "#d0d8de", activeFill: "#f8d855", activeStroke: "#f2b855" },
  "cls-13": { fill: "#0e5796", activeFill: "#39018d", activeStroke: "#efa256" },
  "cls-14": { fill: "#719cc1", activeFill: "#c75290" },
  "cls-15": { fill: "#719cc1", stroke: "#25537b", activeFill: "#c75290", activeStroke: "#4e061a" },
  "cls-16": { fill: "#719cc1", stroke: "#25537b", activeFill: "#c75290", activeStroke: "#4e061a" },
  "cls-17": { fill: "#5689b6", activeFill: "#bf3e33" },
  "cls-18": { fill: "#477fb0", activeFill: "#c03d33" },
  "cls-19": { fill: "#719cc1", stroke: "#edf2f5", activeFill: "#e06667", activeStroke: "#fdcac1" },
  "cls-20": { fill: "#fff", stroke: "#bbd0e2", activeFill: "#f6dfda", activeStroke: "#ccbdb4" },
  "cls-21": { fill: "#fdfdfe", stroke: "#7da4c7", activeStroke: "#ccbdb4" },
  "cls-22": { fill: "#ffffff", stroke: "#7da4c7", activeStroke: "#ccbdb4" },
  "cls-23": { fill: "#e2ebf2", stroke: "#7da4c7", activeFill: "#f6dfda", activeStroke: "#ccbdb4" },
  "cls-24": { fill: "#c3d3e0", stroke: "#7da4c7", activeFill: "#a01d58", activeStroke: "#ccbdb4" },
  "cls-25": { fill: "#bccfe0", activeFill: "#63326e", disabled: true },
  "cls-26": { fill: "#8baecc", activeFill: "#f56f67", disabled: true },
  "cls-27": { fill: "#8eb0ce", activeFill: "#79cc22" },
  "cls-28": { fill: "#5b7994", activeFill: "#b96a04", disabled: true },
  "cls-29": { stroke: "#dde7f0", activeStroke: "#ad341b", disabled: true },
  "cls-30": { fill: "#bed2e3", stroke: "#7b9cb9", activeFill: "#fead99", activeStroke: "#ad341b" },
  "cls-31": { stroke: "#7b9cb9", activeStroke: "#ad341b" },
  "cls-32": { stroke: "#f9fcff", activeStroke: "#ebd7ca", disabled: true },
  "cls-33": { fill: "#7aa2c5", stroke: "#477fb0", activeFill: "#f6554c", activeStroke: "#bb382f" },
  "cls-34": { stroke: "#477fb0", activeStroke: "#bb382f" },
  "cls-35": { fill: "#8aa9cc", stroke: "#ecf2f7", activeFill: "#f49fcc", activeStroke: "#f5f5f5" },
  "cls-36": { fill: "#49627b", activeFill: "#dab077", activeStroke: "#f9c2ad" },
  "cls-37": { fill: "#376d9c", activeFill: "#fff388" },
  "cls-38": { fill: "#3c8ed6", stroke: "#d8d8d8", activeFill: "#10b719", activeStroke: "#ff0" },
  "cls-39": { fill: "#fff", stroke: "#a6c1d8", activeFill: "#fff", activeStroke: "#efc2ae" },
  "cls-40": { fill: "#2869a2", activeFill: "#3e3835" },
  "cls-41": { fill: "#c3d5e5", stroke: "#889198", activeFill: "#edcb57", activeStroke: "#a78c34" },
  "cls-42": { fill: "#c3d5e5", stroke: "#889198", activeFill: "#edcb57", activeStroke: "#a78c34" },
  "cls-bone6": { fill: "#fff", activeFill: "#f49fcc", disabled: true },
  "cls-largeintestine": { fill: "#85a5c1", activeFill: "#e06667" },
  "cls-colon": { fill: "#f5f8fb", stroke: "#9a9999", activeFill: "#b94343", activeStroke: "#fcaea0" },
  "cls-lung": { fill: "#a8c2d9", stroke: "#dde6ec", activeFill: "#fc927e", activeStroke: "#fcaea0" },
  "cls-thymus": { fill: "#a8c2d9", stroke: "#dde6ec", activeFill: "#fc927e", activeStroke: "#fcaea0" },
  "cls-esophagus": {
    fill: "#a8c2d9",
    stroke: "#dde6ec",
    activeFill: "#fc927e",
    activeStroke: "#fcaea0",
    disabled: true,
  },
  "cls-esophagus2": {
    fill: "#a8c2d9",
    stroke: "#dde6ec",
    activeFill: "#fc927e",
    activeStroke: "#fcaea0",
    opacity: 0.5,
    disabled: true,
  },
  "cls-stomach": { fill: "#dde6ec", activeFill: "#ffd6c6", activeStroke: "#fdbeb2" },
  "cls-kidney": { fill: "#3b77aa", activeFill: "#a01d58" },
  "cls-liver": { fill: "#477fb0", activeFill: "#c03d33" },
  "cls-smallintestine": { stroke: "#edf2f5", activeStroke: "#fdcac1" },
  "cls-smallintestine19": { stroke: "#edf2f5", activeStroke: "#fdcac1" },
};
