import { SetStateAction, useState } from "react";
import Grid from "@mui/material/Grid";
import {
  Box,
  Button,
  Checkbox,
  CircularProgress,
  CircularProgressProps,
  FormControl,
  FormControlLabel,
  FormLabel,
  IconButton,
  ListItemText,
  MenuItem,
  Radio,
  RadioGroup,
  Select,
  Stack,
  TextField,
  Tooltip,
  Typography,
} from "@mui/material";
import { Close, Download, InfoOutlined } from "@mui/icons-material";
import { Assays, Conservation, downloadBED, parseGenomicRegion } from "app/downloads/DownloadRange/downloadRangeHelpers";
import { BiosampleTable, EncodeBiosample } from "@weng-lab/ui-components";
import { isAutogeneratedRow } from "@mui/x-data-grid-premium";
import { useApolloClient } from "@apollo/client/react";
import { CCRE_CLASSES, CLASS_DESCRIPTIONS } from "common/consts";
import { reachableCcreClasses } from "common/utility";
import { CcreClass } from "common/types/globalTypes";

function CircularProgressWithLabel(props: CircularProgressProps & { value: number }) {
  return (
    <Box sx={{ position: "relative", display: "inline-flex" }}>
      <CircularProgress variant="determinate" {...props} />
      <Box
        sx={{
          top: 0,
          left: 0,
          bottom: 0,
          right: 0,
          position: "absolute",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <Typography
          variant="caption"
          component="div"
          color="text.secondary"
        >{`${Math.round(props.value)}%`}</Typography>
      </Box>
    </Box>
  );
}

const allAssaysTrue: Assays = {
  atac: true,
  ctcf: true,
  dnase: true,
  h3k27ac: true,
  h3k4me3: true,
};

const DEFAULT_REGION = "chr12:53,380,176-53,416,446"

export const DownloadRange: React.FC = () => {
  const client = useApolloClient();
  const [assembly, setAssembly] = useState<"GRCh38" | "mm10">("GRCh38");
  const [inputValue, setInputValue] = useState<string>(DEFAULT_REGION);
  const [selectedBiosample, setSelectedBiosample] = useState<EncodeBiosample>(null);
  const [bedLoadingPercent, setBedLoadingPercent] = useState<number>(null);
  //Used to disable assay checkboxes
  const [availableAssays, setAvailableAssays] = useState<Assays>(allAssaysTrue);
  //Checkboxes
  const [selectedAssays, setSelectedAssays] = useState<Assays>(allAssaysTrue);
  const [selectedConservation, setSelectedConservation] = useState<Conservation>({
    primate: true,
    mammal: true,
    vertebrate: true,
  });
  //Selected cCRE classes to include in the download
  const [selectedClasses, setSelectedClasses] = useState<CcreClass[]>([...CCRE_CLASSES]);
  //Classes a cCRE can be assigned given the selected biosample's available assays (all classes when none selected)
  const reachableClasses: CcreClass[] = selectedBiosample
    ? reachableCcreClasses(availableAssays)
    : [...CCRE_CLASSES];

  const handleChange = (event: { target: { value: SetStateAction<string> } }) => {
    setInputValue(event.target.value);
  };

  const handleSetAssembly = (value: string) => {
    if (value === "mm10") {
      setSelectedConservation({ primate: null, mammal: null, vertebrate: null });
    } else {
      setSelectedConservation({ primate: true, mammal: true, vertebrate: true });
    }
    handleSetSelectedBiosample(null);
    if (value === "GRCh38" || value === "mm10") {
      setAssembly(value);
    }
  };

  const handleSetSelectedBiosample = (biosample: EncodeBiosample) => {
    setSelectedBiosample(biosample);
    if (biosample) {
      const assays: Assays = {
        atac: !!biosample.atac_experiment_accession,
        ctcf: !!biosample.ctcf_experiment_accession,
        dnase: !!biosample.dnase_experiment_accession,
        h3k27ac: !!biosample.h3k27ac_experiment_accession,
        h3k4me3: !!biosample.h3k4me3_experiment_accession,
      };
      setSelectedAssays(assays);
      setAvailableAssays(assays);
      setSelectedClasses(reachableCcreClasses(assays));
    } else {
      setSelectedAssays(allAssaysTrue);
      setAvailableAssays(allAssaysTrue);
      setSelectedClasses([...CCRE_CLASSES]);
    }
  };

  const handleDownloadBed = () => {
    const region = parseGenomicRegion(inputValue);

    downloadBED({
      client,
      assembly,
      chromosome: region.chromosome,
      start: +region.start,
      end: +region.end,
      biosampleName: selectedBiosample?.name,
      assays: selectedAssays,
      conservation: selectedConservation,
      classes: selectedClasses,
      setBedLoadingPercent,
    });
  };

  return (
    <Grid container spacing={2}>
      <Grid size={{ xs: 12, md: 6 }}>
        <BiosampleTable
          assembly={assembly}
          disableMultipleRowSelection
          disableRowSelectionOnClick={false}
          onSelectionChange={(selected) =>
            selected[0]?.name ? handleSetSelectedBiosample(selected[0]) : handleSetSelectedBiosample(null)
          }
          rowSelectionModel={{ type: "include", ids: new Set(selectedBiosample ? [selectedBiosample?.name] : []) }}
          isRowSelectable={(params) => !isAutogeneratedRow(params.row)}
          // temporary fix while other tables are not setup to group rows
          disableRowGrouping={false}
          divHeight={{ height: 600 }}
        />
      </Grid>
      <Grid size={{ xs: 12, md: 6 }}>
        <Stack spacing={1}>
        <FormControl>
          <FormLabel>Assembly</FormLabel>
          <RadioGroup row value={assembly} onChange={(_, value: string) => handleSetAssembly(value)}>
            <FormControlLabel value="GRCh38" control={<Radio />} label="GRCh38" />
            <FormControlLabel value="mm10" control={<Radio />} label="mm10" />
          </RadioGroup>
        </FormControl>
        <Box>
          <FormLabel>Genomic Region</FormLabel>
          <TextField
            variant="outlined"
            placeholder={DEFAULT_REGION}
            value={inputValue}
            fullWidth
            onChange={handleChange}
          />
        </Box>
        <Box>
          <FormLabel>Selected Biosample</FormLabel>
          <Stack direction="row" alignItems={"center"}>
            <Typography>{`${selectedBiosample ? selectedBiosample.displayname : "N/A"}`}</Typography>
            {selectedBiosample && (
              <IconButton onClick={() => handleSetSelectedBiosample(null)}>
                <Close />
              </IconButton>
            )}
          </Stack>
        </Box>
          <div>
            <Stack direction="row" alignItems="center" spacing={0.5}>
              <FormLabel id="ccre-classes-label">cCRE Classes</FormLabel>
              <Tooltip
                title={
                  "The cCRE classes available for a biosample depend on which assays were performed. " +
                  "Classification is gated by DNase — a biosample without a DNase experiment can only yield " +
                  "“Unclassified.” H3K4me3 enables Promoter and CA-H3K4me3, H3K27ac enables the Proximal/Distal " +
                  "Enhancer classes, and CTCF enables CA-CTCF. ATAC does not affect classification. With no " +
                  "biosample selected, all classes are available (global classification)."
                }
              >
                <IconButton size="small">
                  <InfoOutlined fontSize="small" />
                </IconButton>
              </Tooltip>
            </Stack>
            <Select
              multiple
              size="small"
              displayEmpty
              value={selectedClasses}
              onChange={(e) => setSelectedClasses(e.target.value as CcreClass[])}
              renderValue={(selected) =>
                selected.length === 0
                  ? "None selected"
                  : selected.length === CCRE_CLASSES.length
                    ? "All classes"
                    : selected.map((cls) => CLASS_DESCRIPTIONS[cls]).join(", ")
              }
              aria-labelledby="ccre-classes-label"
              sx={{ minWidth: 220, maxWidth: 260, display: "flex" }}
            >
              {CCRE_CLASSES.map((cls) => (
                <MenuItem key={cls} value={cls} disabled={!reachableClasses.includes(cls)}>
                  <Checkbox checked={selectedClasses.includes(cls)} />
                  <ListItemText primary={CLASS_DESCRIPTIONS[cls]} />
                </MenuItem>
              ))}
            </Select>
          </div>
          <div>
            <FormControlLabel
              label="Assays"
              control={
                <Checkbox
                  //For every available assay, check to make sure it's selected
                  checked={Object.entries(availableAssays).every(
                    (assay: [string, boolean]) => !assay[1] || selectedAssays[assay[0]]
                  )}
                  indeterminate={
                    //True if all available assays are not either true/false at the same time
                    !Object.entries(availableAssays).every(
                      (assay: [string, boolean]) => !assay[1] || selectedAssays[assay[0]]
                    ) &&
                    !Object.entries(availableAssays).every(
                      (assay: [string, boolean]) => !assay[1] || !selectedAssays[assay[0]]
                    )
                  }
                  onChange={(_, checked: boolean) =>
                    setSelectedAssays({
                      atac: availableAssays.atac ? checked : false,
                      ctcf: availableAssays.ctcf ? checked : false,
                      dnase: availableAssays.dnase ? checked : false,
                      h3k27ac: availableAssays.h3k27ac ? checked : false,
                      h3k4me3: availableAssays.h3k4me3 ? checked : false,
                    })
                  }
                />
              }
            />
            <Box sx={{ display: "flex", flexDirection: "row", ml: 3 }}>
              <FormControlLabel
                checked={selectedAssays.dnase}
                onChange={(_, checked: boolean) => setSelectedAssays({ ...selectedAssays, dnase: checked })}
                control={<Checkbox />}
                label={"DNase"}
                disabled={!availableAssays.dnase}
              />
              <FormControlLabel
                checked={selectedAssays.atac}
                onChange={(_, checked: boolean) => setSelectedAssays({ ...selectedAssays, atac: checked })}
                control={<Checkbox />}
                label={"ATAC"}
                disabled={!availableAssays.atac}
              />
              <FormControlLabel
                checked={selectedAssays.ctcf}
                onChange={(_, checked: boolean) => setSelectedAssays({ ...selectedAssays, ctcf: checked })}
                control={<Checkbox />}
                label={"CTCF"}
                disabled={!availableAssays.ctcf}
              />
              <FormControlLabel
                checked={selectedAssays.h3k27ac}
                onChange={(_, checked: boolean) => setSelectedAssays({ ...selectedAssays, h3k27ac: checked })}
                control={<Checkbox />}
                label={"H3K27ac"}
                disabled={!availableAssays.h3k27ac}
              />
              <FormControlLabel
                checked={selectedAssays.h3k4me3}
                onChange={(_, checked: boolean) => setSelectedAssays({ ...selectedAssays, h3k4me3: checked })}
                control={<Checkbox />}
                label={"H3K4me3"}
                disabled={!availableAssays.h3k4me3}
              />
            </Box>
          </div>
          <div>
            <FormControlLabel
              label="Conservation"
              control={
                <Checkbox
                  checked={Object.values(selectedConservation).every((x) => x || x === null) && assembly !== "mm10"}
                  disabled={assembly === "mm10"}
                  indeterminate={
                    !(
                      //If every value is not true/null
                      (
                        Object.values(selectedConservation).every((x) => x || x === null) || //Or every value is not false/null
                        Object.values(selectedConservation).every((x) => !x || x === null)
                      )
                    )
                  }
                  onChange={(_, checked: boolean) =>
                    setSelectedConservation({
                      primate: selectedConservation.primate === null ? null : checked,
                      mammal: selectedConservation.mammal === null ? null : checked,
                      vertebrate: selectedConservation.vertebrate === null ? null : checked,
                    })
                  }
                />
              }
            />
            <Box sx={{ display: "flex", flexDirection: "row", ml: 3 }}>
              <FormControlLabel
                checked={selectedConservation.primate}
                onChange={(_, checked: boolean) =>
                  setSelectedConservation({ ...selectedConservation, primate: checked })
                }
                control={<Checkbox />}
                label={"Primate"}
                disabled={selectedConservation.primate === null || assembly === "mm10"}
              />
              <FormControlLabel
                checked={selectedConservation.mammal}
                onChange={(_, checked: boolean) =>
                  setSelectedConservation({ ...selectedConservation, mammal: checked })
                }
                control={<Checkbox />}
                label={"Mammal"}
                disabled={selectedConservation.mammal === null || assembly === "mm10"}
              />
              <FormControlLabel
                checked={selectedConservation.vertebrate}
                onChange={(_, checked: boolean) =>
                  setSelectedConservation({ ...selectedConservation, vertebrate: checked })
                }
                control={<Checkbox />}
                label={"Vertebrate"}
                disabled={selectedConservation.vertebrate === null || assembly === "mm10"}
              />
            </Box>
          </div>
        </Stack>
        <Stack direction="row" alignItems={"center"} sx={{ mt: 1 }}>
          <Button
            disabled={typeof bedLoadingPercent === "number" || !inputValue || selectedClasses.length === 0}
            variant="outlined"
            sx={{ textTransform: "none" }}
            onClick={handleDownloadBed}
            endIcon={<Download />}
            fullWidth
          >
            Download Search Results (.bed)
          </Button>
          {bedLoadingPercent !== null && <CircularProgressWithLabel value={bedLoadingPercent} />}
        </Stack>
      </Grid>
    </Grid>
  );
};
