import React from "react";
import DownloadContentLayout from "./DownloadContentLayout";
import { Assembly } from "./Annotations";
import {
  allColsHidden,
  BiosampleTable,
  gridVisibleRowsSelector,
  initialTableState,
  useGridApiRef,
  isAutogeneratedRow,
} from "@weng-lab/ui-components";

interface NewAnnotationsByCelltypeProps {
  assembly: Assembly;
}

const AnnotationsByCelltype: React.FC<NewAnnotationsByCelltypeProps> = ({ assembly }) => {
  const overrideInitialTableState = {
    ...initialTableState,
    columns: {
      columnVisibilityModel: {
        ...allColsHidden,
        ontology: true,
        bedurl: true,
      },
    },
  };

  const apiRef = useGridApiRef();

  React.useEffect(() => {
    return apiRef.current?.subscribeEvent("rowExpansionChange", (params, event, details) => {
      const leavesAreVisible = Boolean(
        gridVisibleRowsSelector(apiRef).rows.filter((row) => !isAutogeneratedRow(row.model)).length
      );
      const currentVisibilityModel = details.api.state.columns.columnVisibilityModel;
      if (leavesAreVisible) {
        details.api.setColumnVisibilityModel({
          ...currentVisibilityModel,
          assays: true,
          dnaseZ: true,
          atacZ: true,
          h3k4me3Z: true,
          h3k27ac: true,
          ctcfZ: true,
        });
      } else {
        details.api.setColumnVisibilityModel({
          ...currentVisibilityModel,
          assays: false,
          dnaseZ: false,
          atacZ: false,
          h3k4me3Z: false,
          h3k27ac: false,
          ctcfZ: false,
        });
      }
    });
  }, [apiRef]);

  return (
    <DownloadContentLayout title="cCREs by Cell and Tissue Type">
      <BiosampleTable
        apiRef={apiRef}
        assembly={assembly as "GRCh38" | "mm10"}
        divHeight={{ height: 600 }}
        initialState={overrideInitialTableState}
        //Temporary until we can remove default true value of this prop for all tables
        disableRowGrouping={false}
      />
    </DownloadContentLayout>
  );
};

export default AnnotationsByCelltype;
