import { Box, Stack, Typography } from "@mui/material";
import Image from "next/image";
import EncyclopediaAll from "public/assets/about/images/EncyclopediaAll.png";
import { AboutSection } from "./AboutSection";

export default function EncodeEncyclopedia() {
  return (
    <AboutSection title="The ENCODE Encyclopedia">
      <Box
        sx={{
          display: "grid",
          gridTemplateColumns: { xs: "minmax(0, 1fr)", lg: "2fr 1fr" },
          gap: 4,
          alignItems: "start",
        }}
      >
        <Stack spacing={1}>
          <Typography variant="body1">
            The ENCODE Encyclopedia is an integrated collection of functional genomic annotations derived from
            large-scale experimental data generated by the ENCODE Project. These annotations span multiple conceptual
            layers, including DNA sequence features, regulatory elements, genes and transcripts, and chromatin
            interactions. Some annotations derive directly from primary experimental data, while others reflect
            integrative analyses that combine multiple assays to provide higher-level functional interpretations.
          </Typography>
          <Typography variant="body1">
            SCREEN provides an interactive interface for navigating these annotations, centering many views on cCREs as
            a unifying framework for regulatory analysis.
          </Typography>
        </Stack>
        <Image src={EncyclopediaAll} alt="ENCODE Encyclopedia" style={{ width: "100%", height: "auto" }} />
      </Box>
    </AboutSection>
  );
}
