import { Typography } from "@mui/material";
import { AboutSection, AboutSubsection, Bullet, BulletList } from "./AboutSection";
import BiosampleActivity from "./BiosampleActivity";
import CcreClassification from "./CcreClassification";

export default function RegistryOfCcres() {
  return (
    <AboutSection title="The Registry of Candidate cis-Regulatory Elements (cCREs)">
      <Typography variant="body1">
        The Registry of cCREs is a genome-wide catalog of candidate regulatory elements defined using chromatin
        accessibility, histone modification, and transcription factor binding data generated by ENCODE. The Registry is
        designed to be comprehensive, cell type–agnostic, and extensible as new data become available
      </Typography>
      <AboutSubsection title="Element Anchors">
        <Typography variant="body1">
          In ENCODE4, cCREs are anchored using multiple complementary strategies to capture a broad spectrum of
          regulatory elements:
        </Typography>
        <BulletList>
          <Bullet>
            <b>Representative DNase hypersensitive sites (rDHSs)</b>, generated by clustering DNase-seq peaks across
            large numbers of biosamples, define the majority of accessible regulatory regions.
          </Bullet>
          <Bullet>
            <b>Transcription factor clusters</b>, representing reproducible transcription factor binding sites that do
            not overlap DNase hypersensitive regions, capture regulatory elements with low chromatin accessibility but
            strong, protein-binding signatures.
          </Bullet>
          <Bullet>
            <b>Multi-mapper rDHSs</b>, derived from alignments that retain multi-mapping reads, recover regulatory
            elements in recently duplicated or repetitive genomic regions that were underrepresented in earlier Registry
            versions.
          </Bullet>
        </BulletList>
        <Typography variant="body1">
          Together, these anchors define millions of candidate regulatory elements in the human and mouse genomes.
        </Typography>
      </AboutSubsection>
      <AboutSubsection title="Quantifying Epigenomic Signals">
        <Typography variant="body1">
          For each cCRE anchor, we compute standardized signal summaries for chromatin accessibility (DNase-seq or
          ATAC-seq), histone modifications (H3K4me3 and H3K27ac), and CTCF binding across all available biosamples.
          Signals are converted to Z-scores within each biosample to ensure comparability across assays and experiments.
          These standardized signals form the basis for both classification and biosample-specific activity annotations.
        </Typography>
        <Typography variant="body1">
          cCREs defined using multi-mapping–inclusive chromatin accessibility data do not have associated epigenomic
          signal tracks, as the full set of ENCODE assays was not reprocessed using multi-mapping-inclusive alignments.
          These elements are therefore included in the Registry as candidate regulatory elements but lack quantitative
          signal annotations.
        </Typography>
      </AboutSubsection>
      <CcreClassification />
      <BiosampleActivity />
    </AboutSection>
  );
}
