import React from "react";
import { Dialog, DialogContent } from "@mui/material";
import { BiosampleTable, EncodeBiosample } from "@weng-lab/ui-components";
import { GridRowParams, isAutogeneratedRow } from "@mui/x-data-grid-premium";
import { Assembly } from "common/types/globalTypes";

interface BiosampleSelectProps {
  open: boolean;
  onClose: () => void;
  assembly: Assembly;
  selected: EncodeBiosample;
  onSelectionChange: (biosample: EncodeBiosample) => void;
}

export const BiosampleSelectDialog: React.FC<BiosampleSelectProps> = ({
  assembly,
  selected,
  open,
  onSelectionChange,
  onClose,
}) => {
  const handleSelectionChange = (samples: EncodeBiosample[]) => {
    onSelectionChange(samples[0]); // will only be length one since we specify disableMultipleRowSelection, and are disabling grouped row selection
    onClose();
  };

  // used to apply cursor: "pointer" to clickable leaf nodes
  const getRowClassName = (params: GridRowParams) => {
    if (!isAutogeneratedRow(params.row)) {
      return "is-leaf-row";
    }
    return "";
  };

  return (
    <Dialog open={open} onClose={onClose} maxWidth="sm" fullWidth keepMounted>
      <DialogContent>
        <BiosampleTable
          label={"Select a Biosample"}
          assembly={assembly}
          disableMultipleRowSelection
          isRowSelectable={(params) => !isAutogeneratedRow(params.row)}
          disableRowSelectionOnClick={false}
          onSelectionChange={handleSelectionChange}
          rowSelectionModel={{ type: "include", ids: new Set(selected ? [selected?.name] : []) }}
          divHeight={{ height: "80vh" }}
          getRowClassName={getRowClassName}
          sx={{ "& .is-leaf-row:hover": { cursor: "pointer" } }} // used to apply cursor: "pointer" to clickable leaf nodes
          //temp, remove when enabled in theme
          disableRowGrouping={false}
        />
      </DialogContent>
    </Dialog>
  );
};
