import { ChildCare } from "@mui/icons-material";
import { Treemap, TreemapNode } from "@weng-lab/visualization";
export type ParentTermMetadata = {
  description: string;
  source: string;
};


export const subdisease_treemap: Record<string, TreemapNode<ParentTermMetadata>[]> ={'Metabolic disorder':
[
  { label: "Metabolic disorder", displayValue: 294, style: { color: "#FCB467", labelColor: "#9C5A13" },
  children: [ 
  {label: "Nutritional disorder", value: 93, style: {  labelColor: "#9C5A13" }},
  {label: "Gout", value: 41, style: {labelColor: "#9C5A13" }},
  {label: "Diabetic nephropathy", value: 34, style: {  labelColor: "#9C5A13" }},
  {label: "Inborn errors of metabolism", value: 29, style: { labelColor: "#9C5A13" }},
  {label: "Proteostasis deficiencies", value: 27, style: {  labelColor: "#9C5A13" }},
  {label: "Metabolic syndrome", value: 26, style: {  labelColor: "#9C5A13" }},
  {label: "Diabetic retinopathy", value: 16, style: {  labelColor: "#9C5A13" }},
  {label: "Hyperlipidemia", value: 13, style: { labelColor: "#9C5A13" }},
  {label: "Glucose metabolism disease", value: 11, style: { labelColor: "#9C5A13" }},
  {label: "Acquired metabolic disease", value: 10, style: { labelColor: "#9C5A13" }},
  {label: "Mineral metabolism disease", value: 9, style: {  labelColor: "#9C5A13" }},
  {label: "Disorder of acid-base balance", value: 4, style: { labelColor: "#9C5A13" }},
  {label: "Hypertriglyceridemia", value: 4, style: {  labelColor: "#9C5A13" }},
  {label: "Hyperlipoproteinemia", value: 3, style: {  labelColor: "#9C5A13" }},
  {label: "Carbohydrate metabolism disease", value: 3, style: { labelColor: "#9C5A13" }},
  {label: "Amino acid metabolism disease", value: 3, style: {labelColor: "#9C5A13" }},
  {label: "Bilirubin metabolism disease", value: 2, style: {  labelColor: "#9C5A13" }},
  {label: "Disorder of lipid metabolism", value: 2, style: {  labelColor: "#9C5A13" }},
  {label: "Disorder of purine or pyrimidine metabolism", value: 2, style: {  labelColor: "#9C5A13" }}]}
],'Cardiovascular disease':[{ label: "Cardiovascular disease", displayValue: 649, style: { color: "#B13535", labelColor: "#FFD4D4" }, children: [
  { label: "Vascular disease", value: 469, style: { labelColor: "#FFD4D4" } },
  { label: "Heart disease", value: 300, style: { labelColor: "#FFD4D4" } },
  { label: "Congenital anomaly of cardiovascular system", value: 33, style: { labelColor: "#FFD4D4" } }
] }],
'Biological process':[{ label: "Biological process", displayValue: 1008, style: { color: "#BEBBD9", labelColor: "#676480" }, children:  [
  { label: "Response to stimulus", value: 689, style: { labelColor: "#676480" } },
  { label: "Multicellular organismal process", value: 167, style: { labelColor: "#676480" } },
  { label: "Mental process", value: 89, style: { labelColor: "#676480" } },
  { label: "Developmental process", value: 26, style: { labelColor: "#676480" } },
  { label: "Circadian rhythm", value: 11, style: { labelColor: "#676480" } },
  { label: "Cellular process", value: 8, style: { labelColor: "#676480" } },
  { label: "Energy intake", value: 6, style: { labelColor: "#676480" } },
  { label: "Physical activity", value: 5, style: { labelColor: "#676480" } },
  { label: "Disease course", value: 4, style: { labelColor: "#676480" } },
  { label: "Regulation of biological process", value: 3, style: { labelColor: "#676480" } },
  { label: "Menopause", value: 2, style: { labelColor: "#676480" } },
  { label: "Biological process involved in interspecies interaction between organisms", value: 1, style: { labelColor: "#676480" } },
  { label: "Psychomotor performance", value: 1, style: { labelColor: "#676480" } },
  { label: "Energy expenditure", value: 1, style: { labelColor: "#676480" } },
  { label: "Puberty", value: 1, style: { labelColor: "#676480" } },
  { label: "Reproductive process", value: 1, style: { labelColor: "#676480" } },
  { label: "Pathologic process", value: 1, style: { labelColor: "#676480" } }
] }],
'Neurological disorder': [
  { label: "Neurological disorder", displayValue: 1158, style: { color: "#FFFEB6", labelColor: "#95944D" },
  children: [ 
  {label: "Central nervous system disease", value: 909, style: {  labelColor: "#95944D" }},
  {label: "Hereditary neurological disease", value: 165, style: {labelColor: "#95944D" }},
  {label: "Perceptual disorders", value: 92, style: {  labelColor: "#95944D" }},
  {label: "Retinopathy", value: 86, style: { labelColor: "#95944D" }},
  {label: "Neuropathy", value: 84, style: {  labelColor: "#95944D" }},
  {label: "Sensory system disease", value: 65, style: {  labelColor: "#95944D" }},
  {label: "Peripheral nervous system disease", value: 61, style: {  labelColor: "#95944D" }},
  {label: "Movement disorder", value: 25, style: { labelColor: "#95944D" }},
  {label: "Infectious disorder of the nervous system", value: 24, style: { labelColor: "#95944D" }},
  {label: "Cranial nerve neuropathy", value: 10, style: { labelColor: "#95944D" }},
  {label: "Restless legs syndrome", value: 9, style: {  labelColor: "#95944D" }},
  {label: "Nervous system injury", value: 4, style: { labelColor: "#95944D" }},
  {label: "Autoimmune disorder of the nervous system", value: 4, style: {  labelColor: "#95944D" }},
  {label: "Radiculitis", value: 3, style: {  labelColor: "#95944D" }},
  {label: "Drug-Induced dyskinesia", value: 3, style: { labelColor: "#95944D" }},
  {label: "Neurological pain disorder", value: 3, style: {labelColor: "#95944D" }},
  {label: "Developmental disability", value: 2, style: {  labelColor: "#95944D" }},
  {label: "Congenital nervous system disorder", value: 1, style: {  labelColor: "#95944D" }}
  ]}
], 'Inflammatory measurement': [{ label: "Inflammatory measurement", displayValue: 201, style: { color: "#CDEAC6", labelColor: "#6B8764" }, children: [
  { label: "C-reactive protein measurement", value: 51, style: { labelColor: "#6B8764" } },
  { label: "Interleukin-6 measurement", value: 45, style: { labelColor: "#6B8764" } },
  { label: "Basophil count", value: 22, style: { labelColor: "#6B8764" } },
  { label: "Interleukin 10 measurement", value: 18, style: { labelColor: "#6B8764" } },
  { label: "Interleukin-1 beta measurement", value: 16, style: { labelColor: "#6B8764" } },
  { label: "Interleukin 18 measurement", value: 15, style: { labelColor: "#6B8764" } },
  { label: "Interleukin 1 receptor antagonist measurement", value: 11, style: { labelColor: "#6B8764" } },
  { label: "Interleukin-8 measurement", value: 7, style: { labelColor: "#6B8764" } },
  { label: "CCL11 measurement", value: 5, style: { labelColor: "#6B8764" } },
  { label: "CCL5 measurement", value: 5, style: { labelColor: "#6B8764" } },
  { label: "Interleukin-6 receptor measurement", value: 4, style: { labelColor: "#6B8764" } },
  { label: "CD40 ligand measurement", value: 4, style: { labelColor: "#6B8764" } },
  { label: "YKL40 measurement", value: 2, style: { labelColor: "#6B8764" } },
  { label: "Plasma leucine rich alpha-2-glycoprotein 1 measurement", value: 2, style: { labelColor: "#6B8764" } },
  { label: "CD4:CD8 lymphocyte ratio", value: 1, style: { labelColor: "#6B8764" } }
] },],


'Body measurement': [{ label: "Body measurement", displayValue: 376, style: {  color: "#69CDFE", labelColor: "#f9719B"  }, children: [ { label: "Body mass index", value: 186, style: { labelColor: "#f9719B" } },
  { label: "Body ratio measurement", value: 68, style: { labelColor: "#f9719B" } },
  { label: "Body composition measurement", value: 45, style: { labelColor: "#f9719B" } },
  { label: "Body weight", value: 37, style: { labelColor: "#f9719B" } },
  { label: "Hip geometry", value: 18, style: { labelColor: "#f9719B" } },
  { label: "BMI-adjusted waist circumference", value: 10, style: { labelColor: "#f9719B" } },
  { label: "BMI-adjusted hip circumference", value: 8, style: { labelColor: "#f9719B" } },
  { label: "Body height at birth", value: 3, style: { labelColor: "#f9719B" } },
  { label: "Infant body height", value: 1, style: { labelColor: "#f9719B" } },
  { label: "Intertrochanteric region size", value: 1, style: { labelColor: "#f9719B" } },
  { label: "Arm span", value: 1, style: { labelColor: "#f9719B" } }]}],

  'Cancer':[{ label: "Cancer", displayValue: 1169, style: {  color: "#BB82BC", labelColor: "#683569"   },children: [
  { label: "Rare genetic tumor", value: 104, style: { labelColor: "#683569" } },
  { label: "Hematopoietic and lymphoid system neoplasm", value: 102, style: { labelColor: "#683569" } },
  { label: "Respiratory system cancer", value: 97, style: { labelColor: "#683569" } },
  { label: "Digestive system neoplasm", value: 64, style: { labelColor: "#683569" } },
  { label: "Malignant endocrine neoplasm", value: 50, style: { labelColor: "#683569" } },
  { label: "Endocrine neoplasm", value: 49, style: { labelColor: "#683569" } },
  { label: "Benign neoplasm", value: 48, style: { labelColor: "#683569" } },
  { label: "Fibrosis", value: 47, style: { labelColor: "#683569" } },
  { label: "Malignant urinary system neoplasm", value: 45, style: { labelColor: "#683569" } },
  { label: "Nervous system neoplasm", value: 43, style: { labelColor: "#683569" } },
  { label: "Immune system cancer", value: 37, style: { labelColor: "#683569" } },
  { label: "Nervous system cancer", value: 34, style: { labelColor: "#683569" } },
  { label: "Head and neck malignant neoplasia", value: 33, style: { labelColor: "#683569" } },
  { label: "Reproductive system neoplasm", value: 27, style: { labelColor: "#683569" } },
  { label: "Connective tissue neoplasm", value: 24, style: { labelColor: "#683569" } },
  { label: "Respiratory system neoplasm", value: 24, style: { labelColor: "#683569" } },
  { label: "Neoplasm of thorax", value: 22, style: { labelColor: "#683569" } },
  { label: "Skin neoplasm", value: 20, style: { labelColor: "#683569" } },
  { label: "Mesenchymal cell neoplasm", value: 20, style: { labelColor: "#683569" } },
  { label: "Melanocytic neoplasm", value: 19, style: { labelColor: "#683569" } },
  { label: "Virus associated tumor", value: 14, style: { labelColor: "#683569" } },
  { label: "Epithelial neoplasm", value: 14, style: { labelColor: "#683569" } },
  { label: "Head and neck neoplasia", value: 14, style: { labelColor: "#683569" } },
  { label: "Musculoskeletal system cancer", value: 13, style: { labelColor: "#683569" } },
  { label: "Embryonal neoplasm", value: 9, style: { labelColor: "#683569" } },
  { label: "Connective and soft tissue neoplasm", value: 8, style: { labelColor: "#683569" } },
  { label: "Secondary malignant neoplasm", value: 7, style: { labelColor: "#683569" } },
  { label: "Myeloproliferative disorder", value: 7, style: { labelColor: "#683569" } },
  { label: "High grade malignant neoplasm", value: 7, style: { labelColor: "#683569" } },
  { label: "Sarcoma", value: 6, style: { labelColor: "#683569" } },
  { label: "Germ cell tumor", value: 6, style: { labelColor: "#683569" } },
  { label: "Pre-malignant neoplasm", value: 4, style: { labelColor: "#683569" } },
  { label: "Cardiovascular neoplasm", value: 4, style: { labelColor: "#683569" } },
  { label: "Upper aerodigestive tract neoplasm", value: 2, style: { labelColor: "#683569" } },
  { label: "Childhood cancer", value: 1, style: { labelColor: "#683569" } },
  { label: "Urinary system neoplasm", value: 1, style: { labelColor: "#683569" } },
  { label: "Odontogenic cyst", value: 1, style: { labelColor: "#683569" } },
  { label: "Malignant mixed neoplasm", value: 1, style: { labelColor: "#683569" } }
]
}],
'Cardiovascular measurement':[{ label: "Cardiovascular measurement", displayValue: 726, style: { color: "#81B2D2", labelColor: "#335E7A" }, children:  [
  { label: "Cardiovascular disease biomarker measurement", value: 370, style: { labelColor: "#335E7A" } },
  { label: "Systolic blood pressure", value: 103, style: { labelColor: "#335E7A" } },
  { label: "Diastolic blood pressure", value: 100, style: { labelColor: "#335E7A" } },
  { label: "Uric acid measurement", value: 37, style: { labelColor: "#335E7A" } },
  { label: "Left ventricular structural measurement", value: 30, style: { labelColor: "#335E7A" } },
  { label: "Mean arterial pressure", value: 20, style: { labelColor: "#335E7A" } },
  { label: "Aortic measurement", value: 17, style: { labelColor: "#335E7A" } },
  { label: "Left ventricular diastolic function measurement", value: 12, style: { labelColor: "#335E7A" } },
  { label: "Creatine kinase measurement", value: 12, style: { labelColor: "#335E7A" } },
  { label: "Homocysteine measurement", value: 11, style: { labelColor: "#335E7A" } },
  { label: "Left ventricular systolic function measurement", value: 7, style: { labelColor: "#335E7A" } },
  { label: "Cardiovascular age measurement", value: 3, style: { labelColor: "#335E7A" } },
  { label: "Right ventricular diastolic volume measurement", value: 3, style: { labelColor: "#335E7A" } },
  { label: "Early cardiac repolarization measurement", value: 2, style: { labelColor: "#335E7A" } },
  { label: "Right ventricular systolic volume measurement", value: 2, style: { labelColor: "#335E7A" } },
  { label: "Mitral valve annular diameter", value: 2, style: { labelColor: "#335E7A" } },
  { label: "Vascular endothelial function measurement", value: 2, style: { labelColor: "#335E7A" } },
  { label: "Left ventricle sphericity index", value: 1, style: { labelColor: "#335E7A" } }
]}],
'Digestive system disorder': [{ label: "Digestive system disorder", displayValue: 684, style: { color: "#B6704F", labelColor: "#2F0F00" }, children:  [
  { label: "Gastrointestinal disease", value: 224, style: { labelColor: "#2F0F00" } },
  { label: "Pancreas disease", value: 183, style: { labelColor: "#2F0F00" } },
  { label: "Hepatobiliary disease", value: 159, style: { labelColor: "#2F0F00" } },
  { label: "Esophageal disease", value: 65, style: { labelColor: "#2F0F00" } },
  { label: "Mouth disease", value: 51, style: { labelColor: "#2F0F00" } },
  { label: "Digestive system infectious disorder", value: 41, style: { labelColor: "#2F0F00" } },
  { label: "Peptic ulcer disease", value: 27, style: { labelColor: "#2F0F00" } },
  { label: "Periodontitis", value: 20, style: { labelColor: "#2F0F00" } },
  { label: "Disease of peritoneum", value: 3, style: { labelColor: "#2F0F00" } },
  { label: "Gastrointestinal polyp", value: 1, style: { labelColor: "#2F0F00" } },
  { label: "Diarrheal disease", value: 1, style: { labelColor: "#2F0F00" } },
  { label: "Flatulence", value: 1, style: { labelColor: "#2F0F00" } },
  { label: "Small intestine enteropathy", value: 1, style: { labelColor: "#2F0F00" } }
]
 }],
 'Hematological measurement': [{ label: "Hematological measurement", displayValue: 568, style: { color: "#90D3C7", labelColor: "#3B776C" } , children: [
  { label: "Complete blood cell count", value: 229, style: { labelColor: "#3B776C" } },
  { label: "Hemoglobin measurement", value: 157, style: { labelColor: "#3B776C" } },
  { label: "Erythrocyte indices", value: 98, style: { labelColor: "#3B776C" } },
  { label: "Neutrophil measurement", value: 62, style: { labelColor: "#3B776C" } },
  { label: "Monocyte measurement", value: 49, style: { labelColor: "#3B776C" } },
  { label: "Eosinophil measurement", value: 48, style: { labelColor: "#3B776C" } },
  { label: "Hematocrit", value: 32, style: { labelColor: "#3B776C" } },
  { label: "Basophil measurement", value: 17, style: { labelColor: "#3B776C" } },
  { label: "Prothrombin time measurement", value: 15, style: { labelColor: "#3B776C" } },
  { label: "Hemorheological measurement", value: 7, style: { labelColor: "#3B776C" } },
  { label: "Haptoglobin measurement", value: 6, style: { labelColor: "#3B776C" } },
  { label: "L lactate dehydrogenase measurement", value: 6, style: { labelColor: "#3B776C" } },
  { label: "Total blood protein measurement", value: 6, style: { labelColor: "#3B776C" } },
  { label: "Platelet crit", value: 5, style: { labelColor: "#3B776C" } },
  { label: "Platelet component distribution width", value: 5, style: { labelColor: "#3B776C" } },
  { label: "Factor VIII measurement", value: 4, style: { labelColor: "#3B776C" } },
  { label: "Factor XI measurement", value: 3, style: { labelColor: "#3B776C" } },
  { label: "Protein S measurement", value: 2, style: { labelColor: "#3B776C" } },
  { label: "Protein C measurement", value: 2, style: { labelColor: "#3B776C" } },
  { label: "Lymphocyte:monocyte ratio", value: 2, style: { labelColor: "#3B776C" } },
  { label: "Neutrophil-to-lymphocyte ratio", value: 2, style: { labelColor: "#3B776C" } },
  { label: "Platelet-to-lymphocyte ratio", value: 2, style: { labelColor: "#3B776C" } },
  { label: "Myeloperoxidase (MPO)-DNA complex measurement", value: 2, style: { labelColor: "#3B776C" } },
  { label: "Immature platelet measurement", value: 1, style: { labelColor: "#3B776C" } },
  { label: "Monocyte:lymphocyte ratio", value: 1, style: { labelColor: "#3B776C" } },
  { label: "Immature reticulocyte measurement", value: 1, style: { labelColor: "#3B776C" } },
  { label: "Trimethyllysine measurement", value: 1, style: { labelColor: "#3B776C" } },
  { label: "C3d:C3 ratio", value: 1, style: { labelColor: "#3B776C" } }
]
}],
'Immune system disorder':[{ label: "Immune system disorder", displayValue: 587, style: { color: "#FFEC76", labelColor: "#988612" } , children:  [
  { label: "Hypersensitivity reaction disease", value: 398, style: { labelColor: "#988612" } },
  { label: "Autoimmune disease", value: 329, style: { labelColor: "#988612" } },
  { label: "Psoriasis", value: 41, style: { labelColor: "#988612" } },
  { label: "Lymphoid system disorder", value: 20, style: { labelColor: "#988612" } },
  { label: "Acute graft vs. host disease", value: 15, style: { labelColor: "#988612" } },
  { label: "Leukocyte disorder", value: 15, style: { labelColor: "#988612" } },
  { label: "Spondyloarthropathy", value: 13, style: { labelColor: "#988612" } },
  { label: "Myositis", value: 13, style: { labelColor: "#988612" } },
  { label: "Immunodeficiency disease", value: 9, style: { labelColor: "#988612" } },
  { label: "Inborn error of immunity", value: 6, style: { labelColor: "#988612" } },
  { label: "Graft versus host disease", value: 5, style: { labelColor: "#988612" } },
  { label: "Bone marrow disorder", value: 4, style: { labelColor: "#988612" } },
  { label: "Immune system toxicity", value: 1, style: { labelColor: "#988612" } }
]
 }],
'Lipid or lipoprotein measurement':  [
  { label: "Lipid or lipoprotein measurement", displayValue: 2123, style: { color: "#B5DD6E", labelColor: "#525D3D" },
  children:  [
  { label: "Triglyceride measurement", value: 456, style: { labelColor: "#525D3D" } },
  { label: "High density lipoprotein cholesterol measurement", value: 241, style: { labelColor: "#525D3D" } },
  { label: "Sphingomyelin measurement", value: 218, style: { labelColor: "#525D3D" } },
  { label: "Cholesteryl ester measurement", value: 156, style: { labelColor: "#525D3D" } },
  { label: "Lysophosphatidylcholine measurement", value: 104, style: { labelColor: "#525D3D" } },
  { label: "Glycerophospholipid measurement", value: 88, style: { labelColor: "#525D3D" } },
  { label: "Lysophosphatidylethanolamine measurement", value: 51, style: { labelColor: "#525D3D" } },
  { label: "Testosterone measurement", value: 51, style: { labelColor: "#525D3D" } },
  { label: "Polyunsaturated fatty acid measurement", value: 37, style: { labelColor: "#525D3D" } },
  { label: "Linoleic acid measurement", value: 25, style: { labelColor: "#525D3D" } },
  { label: "Esterified cholesterol measurement", value: 23, style: { labelColor: "#525D3D" } },
  { label: "Docosahexaenoic acid measurement", value: 21, style: { labelColor: "#525D3D" } },
  { label: "Estradiol measurement", value: 17, style: { labelColor: "#525D3D" } },
  { label: "Cortisol measurement", value: 10, style: { labelColor: "#525D3D" } },
  { label: "Dehydroepiandrosterone sulphate measurement", value: 9, style: { labelColor: "#525D3D" } },
  { label: "Epiandrosterone sulfate measurement", value: 7, style: { labelColor: "#525D3D" } },
  { label: "Ketone body measurement", value: 7, style: { labelColor: "#525D3D" } },
  { label: "Glycerophosphoethanolamine measurement", value: 6, style: { labelColor: "#525D3D" } },
  { label: "Androsterone sulfate measurement", value: 6, style: { labelColor: "#525D3D" } },
  { label: "Phosphatidylcholine 38:5 measurement", value: 6, style: { labelColor: "#525D3D" } },
  { label: "Triglyceride:HDL cholesterol ratio", value: 5, style: { labelColor: "#525D3D" } },
  { label: "Oleoyl ethanolamide measurement", value: 5, style: { labelColor: "#525D3D" } },
  { label: "Thymol sulfate measurement", value: 5, style: { labelColor: "#525D3D" } },
  { label: "Pregnenolone sulfate measurement", value: 4, style: { labelColor: "#525D3D" } },
  { label: "Phosphatidylcholine 38:2 measurement", value: 4, style: { labelColor: "#525D3D" } },
  { label: "Phosphatidylcholine 38:6 measurement", value: 4, style: { labelColor: "#525D3D" } },
  { label: "Phosphatidylcholine 38:4 measurement", value: 4, style: { labelColor: "#525D3D" } },
  { label: "Carotenoid measurement", value: 4, style: { labelColor: "#525D3D" } },
  { label: "Phytosterol measurement", value: 4, style: { labelColor: "#525D3D" } },
  { label: "Diacylglycerol 36:2 measurement", value: 4, style: { labelColor: "#525D3D" } },
  { label: "Diacylglycerol 34:2 measurement", value: 4, style: { labelColor: "#525D3D" } },
  { label: "Cholic acid glucuronide measurement", value: 4, style: { labelColor: "#525D3D" } },
  { label: "Acetone measurement", value: 4, style: { labelColor: "#525D3D" } },
  { label: "Linolenic acid measurement", value: 3, style: { labelColor: "#525D3D" } },
  { label: "Phosphatidylcholine 40:8 measurement", value: 3, style: { labelColor: "#525D3D" } },
  { label: "Phosphatidylcholine 34:5 measurement", value: 3, style: { labelColor: "#525D3D" } },
  { label: "Diacylglycerol 36:1 measurement", value: 3, style: { labelColor: "#525D3D" } },
  { label: "Diacylglycerol 36:3 measurement", value: 3, style: { labelColor: "#525D3D" } },
  { label: "Eicosapentaenoic acid measurement", value: 3, style: { labelColor: "#525D3D" } },
  { label: "Diacylglycerol 36:4 measurement", value: 3, style: { labelColor: "#525D3D" } },
  { label: "Campesterol measurement", value: 3, style: { labelColor: "#525D3D" } },
  { label: "Phosphatidylcholine 38:3 measurement", value: 3, style: { labelColor: "#525D3D" } },
  { label: "Linoleoyl ethanolamide measurement", value: 3, style: { labelColor: "#525D3D" } },
  { label: "Phosphatidylcholine 39:5 measurement", value: 3, style: { labelColor: "#525D3D" } },
  { label: "Phosphatidylcholine 34:4 measurement", value: 3, style: { labelColor: "#525D3D" } },
  { label: "Sphinganine measurement", value: 3, style: { labelColor: "#525D3D" } },
  { label: "Diacylglycerol 34:1 measurement", value: 3, style: { labelColor: "#525D3D" } },
  { label: "Phosphatidylcholine 36:0 measurement", value: 2, style: { labelColor: "#525D3D" } },
  { label: "Diacylglycerol 34:0 measurement", value: 2, style: { labelColor: "#525D3D" } },
  { label: "Diacylglycerol 38:4 measurement", value: 2, style: { labelColor: "#525D3D" } },
  { label: "Phosphatidylcholine 36:4 measurement", value: 2, style: { labelColor: "#525D3D" } },
  { label: "Phosphatidylcholine 36:3 measurement", value: 2, style: { labelColor: "#525D3D" } },
  { label: "Docosapentaenoic acid measurement", value: 2, style: { labelColor: "#525D3D" } },
  { label: "Diacylglycerol 38:5 measurement", value: 2, style: { labelColor: "#525D3D" } },
  { label: "Phosphatidylcholine 34:2 measurement", value: 2, style: { labelColor: "#525D3D" } },
  { label: "Phosphatidylcholine 32:2 measurement", value: 2, style: { labelColor: "#525D3D" } },
  { label: "Diacylglycerol 34:3 measurement", value: 2, style: { labelColor: "#525D3D" } },
  { label: "Adrenal suppression measurement", value: 2, style: { labelColor: "#525D3D" } },
  { label: "Phosphatidylcholine 35:5 measurement", value: 2, style: { labelColor: "#525D3D" } },
  { label: "Phosphatidylcholine 40:7 measurement", value: 2, style: { labelColor: "#525D3D" } },
  { label: "Phosphatidylcholine 36:5 measurement", value: 2, style: { labelColor: "#525D3D" } },
  { label: "Diacylglycerol 36:5 measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Diacylglycerol 38:3 measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Estrone measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Phosphatidylcholine 38:7 measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Phosphatidylcholine 36:6 measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Total cholesterol in small VLDL", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Vitamin D dietary intake measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Diacylglycerol 33:1 measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Sorbate measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Total cholesterol in large VLDL", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Total cholesterol in medium VLDL", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Adipic acid measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Dehydroepiandrosterone measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Cortisol:DHEAS ratio measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Cholesterol efflux capacity measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Hepatic lipid content measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Glycocholic acid measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Glycochenodeoxycholic acid measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Glycerophosphorylcholine measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Phosphatidylcholine 36:1 measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Phosphatidylcholine 34:3 measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Pimelic acid measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Phosphatidylcholine 40:6 measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Phosphatidylcholine 32:1 measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Phosphatidylcholine 34:1 measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Phosphatidylcholine 32:0 measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Glycerophosphocholine measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Non-HDL cholesterol:HDL cholesterol ratio", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Suberic acid measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Cholesterol esters in large VLDL measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Propionic acid measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Palmitoleic acid measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Phosphatidylcholine 28:0 measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Cholesterol esters in medium VLDL measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Cortisone measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Phosphatidylcholine 33:0 measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Phosphatidylcholine 31:0 measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Phosphatidylcholine 33:2 measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Phosphatidylcholine 33:1 measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Cholesteryl ester transfer protein measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Phosphatidylcholine 36:2 measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "17-hydroxyprogesterone measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Arachidonic acid measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "Low density lipoprotein cholesterol measurement", value: 189, style: { labelColor: "#525D3D" } },
  { label: "Total cholesterol measurement", value: 151, style: { labelColor: "#525D3D" } },
  { label: "Free cholesterol measurement", value: 78, style: { labelColor: "#525D3D" } },
  { label: "Intermediate density lipoprotein measurement", value: 22, style: { labelColor: "#525D3D" } },
  { label: "Apolipoprotein A 1 measurement", value: 16, style: { labelColor: "#525D3D" } },
  { label: "Apolipoprotein B measurement", value: 16, style: { labelColor: "#525D3D" } },
  { label: "Lipoprotein A measurement", value: 13, style: { labelColor: "#525D3D" } },
  { label: "Non-high density lipoprotein cholesterol measurement", value: 10, style: { labelColor: "#525D3D" } },
  { label: "Lipoprotein-associated phospholipase A(2) measurement", value: 4, style: { labelColor: "#525D3D" } },
  { label: "Apolipoprotein A-IV measurement", value: 3, style: { labelColor: "#525D3D" } },
  { label: "Clusterin measurement", value: 2, style: { labelColor: "#525D3D" } },
  { label: "LDL peak particle diameter measurement", value: 1, style: { labelColor: "#525D3D" } },
  { label: "LDL cholesterol:HDL cholesterol ratio", value: 1, style: { labelColor: "#525D3D" } }
]
  
  }
]  }
export const tree: TreemapNode<ParentTermMetadata>[] = [
  //{ label: "Other measurement", value: 31657, style: { color: "#056798", labelColor: "#58C1E5" } },
  { label: "Lipid or lipoprotein measurement", value: 2123, style: { color: "#B5DD6E", labelColor: "#525D3D" }},
  { label: "Other disease", value: 1676, style: { color: "#FC3C99", labelColor: "#840040" } },
  { label: "Other trait", value: 1273, style: { color: "#F98174", labelColor: "#953227" } },
  { label: "Cancer", value: 1169, style: { color: "#BB82BC", labelColor: "#683569" } },
  { label: "Neurological disorder", value: 1158, style: { color: "#FFFEB6", labelColor: "#95944D" } },
  { label: "Biological process", value: 1008, style: { color: "#BEBBD9", labelColor: "#676480" } },
  { label: "Cardiovascular measurement", value: 726, style: { color: "#81B2D2", labelColor: "#335E7A" } },
  { label: "Digestive system disorder", value: 684, style: { color: "#B6704F", labelColor: "#2F0F00" } },
  { label: "Cardiovascular disease", value: 649, style: { color: "#B13535", labelColor: "#FFD4D4" } },
  { label: "Immune system disorder", value: 587, style: { color: "#FFEC76", labelColor: "#988612" } },
  { label: "Hematological measurement", value: 568, style: { color: "#90D3C7", labelColor: "#3B776C" } },
  { label: "Body measurement", value: 376, style: { color: "#69CDFE", labelColor: "#f9719B" } },
  { label: "Metabolic disorder", value: 294, style: { color: "#FCB467", labelColor: "#9C5A13" } },
  { label: "Inflammatory measurement", value: 201, style: { color: "#CDEAC6", labelColor: "#6B8764" } },
];


