import React, { useState, useEffect } from "react";
import Dialog from "@mui/material/Dialog";
import DialogContent from "@mui/material/DialogContent";
import Button from "@mui/material/Button";
import Box from "@mui/material/Box";
import { Table, TableColDef } from "@weng-lab/ui-components";
import {
  GridRenderCellParams,
  GridRowSelectionModel,
  GridSlotsComponentsProps,
  GridGroupingColDefOverride,
  isAutogeneratedRow,
  GridInitialState,
  useGridApiRef,
} from "@mui/x-data-grid-premium";
import { capitalizeFirstLetter } from "common/utility";
import { SpeciesRow } from "./utils";

interface SpeciesSelectProps {
  open: boolean;
  onClose: () => void;
  species: SpeciesRow[];
  selectedSpecies: Set<string>;
  onSelectionChange: (newSelected: Set<string>) => void;
  fullWidth?: boolean;
  maxWidth?: false | "xs" | "sm" | "md" | "lg" | "xl";
}

const groupingColDef: GridGroupingColDefOverride<SpeciesRow> = {
  headerName: "Order",
};

const columns: TableColDef[] = [
  {
    headerName: "Common Name",
    field: "displayName",
  },
  {
    headerName: "Species",
    field: "id",
    valueFormatter: (v: string) => v?.replaceAll("_", " "),
  },
  {
    headerName: "Order",
    field: "order",
    valueFormatter: (v: string) => capitalizeFirstLetter(v.toLowerCase()),
  },
  {
    headerName: "Sequence Coverage",
    field: "coverage",
    type: "number",
    renderCell: (params: GridRenderCellParams) => {
      return `${isAutogeneratedRow(params.row) ? "Avg - " : ""}${(params.value * 100).toFixed(1)}%`;
    },
  },
];

const initialState: GridInitialState = {
  sorting: {
    sortModel: [{ field: "coverage", sort: "desc" } as const],
  },
  rowGrouping: {
    model: ["order"],
  },
  aggregation: {
    model: {
      coverage: "avg",
    },
  },
};

//tell ts that these are the new footer props
declare module "@mui/x-data-grid-premium" {
  interface FooterPropsOverrides {
    handleSubmit: () => void;
    handleCancel: () => void;
  }
}

const CustomFooterWithActions = (props: NonNullable<GridSlotsComponentsProps["footer"]>) => (
  <Box
    width={"100%"}
    p={1}
    borderTop={(theme) => `1px solid ${theme.palette.divider}`}
    display="flex"
    justifyContent="flex-end"
    gap={1}
  >
    <Button onClick={props.handleCancel}>Cancel</Button>
    <Button onClick={props.handleSubmit} variant="contained">
      Apply
    </Button>
  </Box>
);

const SpeciesSelect: React.FC<SpeciesSelectProps> = ({
  open,
  onClose,
  species,
  selectedSpecies,
  onSelectionChange,
  fullWidth = true,
  maxWidth = "lg",
}) => {
  const [pendingSelection, setPendingSelection] = useState<Set<string>>(new Set(selectedSpecies));

  // Update pending selection when dialog opens
  useEffect(() => {
    if (open) {
      setPendingSelection(new Set(selectedSpecies));
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open]);

  const handleSelectionChange = (rowSelectionModel: GridRowSelectionModel) => {
    setPendingSelection(rowSelectionModel.ids as Set<string>);
  };

  //filter out autogenerated group rows before calling onSelectionChange
  const handleSubmit = () => {
    const ids = [...pendingSelection.values()];
    const rows = ids.map((id) => apiRef.current.getRow<SpeciesRow>(id));
    const filtered = rows.filter((row) => !isAutogeneratedRow(row)).map((row) => row.id);
    onSelectionChange(new Set(filtered));
    onClose();
  };

  const handleCancel = () => {
    setPendingSelection(new Set(selectedSpecies));
    onClose();
  };

  const apiRef = useGridApiRef();

  return (
    <Dialog
      open={open}
      onClose={handleCancel}
      fullWidth={fullWidth}
      maxWidth={maxWidth}
      aria-labelledby="species-select-title"
    >
      <DialogContent>
        <Table
          apiRef={apiRef}
          label={"Select Species for Sequence Alignment Plot"}
          columns={columns}
          rows={species}
          checkboxSelection
          disableRowSelectionExcludeModel
          onRowSelectionModelChange={handleSelectionChange}
          rowSelectionModel={{ type: "include", ids: pendingSelection }}
          divHeight={{ height: "80vh" }}
          initialState={initialState}
          disableRowGrouping={false} //needed since we global disabled grouping in theme bc most tables not setup for it
          groupingColDef={groupingColDef}
          slots={{ footer: CustomFooterWithActions }}
          slotProps={{ footer: { handleSubmit, handleCancel } }}
        />
      </DialogContent>
    </Dialog>
  );
};

export default SpeciesSelect;
