import { Nucleotide, TreeItem } from "@weng-lab/visualization";
import data241 from "./241_mammals_treedata.json";

export const ORDERS = [
  "PRIMATES",
  "DERMOPTERA",
  "CARNIVORA",
  "LAGOMORPHA",
  "CETARTIODACTYLA",
  "RODENTIA",
  "HYRACOIDEA",
  "PERISSODACTYLA",
  "CHIROPTERA",
  "EULIPOTYPHLA",
  "PHOLIDOTA",
  "PILOSA",
  "AFROSORICIDA",
  "SIRENIA",
  "TUBULIDENTATA",
  "PROBOSCIDEA",
  "SCANDENTIA",
  "CINGULATA",
  "MACROSCELIDEA",
] as const;

type Order = (typeof ORDERS)[number];

export type SpeciesRow = {
  id: string;
  displayName: string;
  order: string;
  coverage: number;
};

export interface SpeciesMeta {
  displayName: string;
  order: Order;
}

export const SPECIES_META: Record<string, SpeciesMeta> = {
  Galeopterus_variegatus: { displayName: "Sunda Flying Lemur", order: "DERMOPTERA" },
  Hyaena_hyaena: { displayName: "Striped Hyena", order: "CARNIVORA" },
  Lepus_americanus: { displayName: "Snowshoe Hare", order: "LAGOMORPHA" },
  Panthera_pardus: { displayName: "Leopard", order: "CARNIVORA" },
  Pantholops_hodgsonii: { displayName: "Chiru", order: "CETARTIODACTYLA" },
  Dolichotis_patagonum: { displayName: "Patagonian Mara", order: "RODENTIA" },
  Oryctolagus_cuniculus: { displayName: "Rabbit", order: "LAGOMORPHA" },
  Callithrix_jacchus: { displayName: "White Tufted Ear Marmoset", order: "PRIMATES" },
  Mellivora_capensis: { displayName: "Honey Badger", order: "CARNIVORA" },
  Microcebus_murinus: { displayName: "Gray Mouse Lemur", order: "PRIMATES" },
  Papio_anubis: { displayName: "Olive Baboon", order: "PRIMATES" },
  Procavia_capensis: { displayName: "South African Rock Hyrax", order: "HYRACOIDEA" },
  Equus_caballus: { displayName: "Horse", order: "PERISSODACTYLA" },
  Sus_scrofa: { displayName: "Pig", order: "CETARTIODACTYLA" },
  Moschus_moschiferus: { displayName: "Siberian Musk Deer", order: "CETARTIODACTYLA" },
  Puma_concolor: { displayName: "Puma", order: "CARNIVORA" },
  Pongo_abelii: { displayName: "Sumatran Orangutan", order: "PRIMATES" },
  Heterohyrax_brucei: { displayName: "African Yellow Spotted Rock Hyrax", order: "HYRACOIDEA" },
  Sigmodon_hispidus: { displayName: "Hispid Cotton Rat", order: "RODENTIA" },
  Ctenomys_sociabilis: { displayName: "Social Tuco Tuco", order: "RODENTIA" },
  Spermophilus_dauricus: { displayName: "Daurian Ground Squirrel", order: "RODENTIA" },
  Piliocolobus_tephrosceles: { displayName: "Ugandan Red Colobus", order: "PRIMATES" },
  Tonatia_saurophila: { displayName: "Stripe Headed Round Eared Bat", order: "CHIROPTERA" },
  Ammotragus_lervia: { displayName: "Aoudad", order: "CETARTIODACTYLA" },
  Crocidura_indochinensis: { displayName: "Indochinese Shrew", order: "EULIPOTYPHLA" },
  Hipposideros_galeritus: { displayName: "Cantors Leaf Nosed Bat", order: "CHIROPTERA" },
  Dicerorhinus_sumatrensis: { displayName: "Sumatran Rhinoceros", order: "PERISSODACTYLA" },
  Manis_pentadactyla: { displayName: "Chinese Pangolin", order: "PHOLIDOTA" },
  Miniopterus_schreibersii: { displayName: "Common Bent Wing Bat", order: "CHIROPTERA" },
  Cebus_albifrons: { displayName: "White Fronted Capuchin", order: "PRIMATES" },
  Bos_mutus: { displayName: "Wild Yak", order: "CETARTIODACTYLA" },
  Nycticebus_coucang: { displayName: "Sunda Slow Loris", order: "PRIMATES" },
  Myrmecophaga_tridactyla: { displayName: "Giant Anteater", order: "PILOSA" },
  Macaca_nemestrina: { displayName: "Pig Tailed Macaque", order: "PRIMATES" },
  Mus_caroli: { displayName: "Ryukyu Mouse", order: "RODENTIA" },
  Ochotona_princeps: { displayName: "American Pika", order: "LAGOMORPHA" },
  Tursiops_truncatus: { displayName: "Bottlenose Dolphin", order: "CETARTIODACTYLA" },
  Zalophus_californianus: { displayName: "California Sea Lion", order: "CARNIVORA" },
  Nannospalax_galili: { displayName: "Upper Galilee Mountains Blind Mole Rat", order: "RODENTIA" },
  Ailuropoda_melanoleuca: { displayName: "Giant Panda", order: "CARNIVORA" },
  Equus_przewalskii: { displayName: "Przewalskis Horse", order: "PERISSODACTYLA" },
  Panthera_tigris: { displayName: "Amur Tiger", order: "CARNIVORA" },
  Saimiri_boliviensis: { displayName: "Bolivian Squirrel Monkey", order: "PRIMATES" },
  Echinops_telfairi: { displayName: "Small Madagascar Hedgehog", order: "AFROSORICIDA" },
  Onychomys_torridus: { displayName: "Scorpion Mouse", order: "RODENTIA" },
  Ellobius_lutescens: { displayName: "Transcaucasian Mole Vole", order: "RODENTIA" },
  Peromyscus_maniculatus: { displayName: "Prairie Deer Mouse", order: "RODENTIA" },
  Condylura_cristata: { displayName: "Star Nosed Mole", order: "EULIPOTYPHLA" },
  Camelus_ferus: { displayName: "Wild Bactrian Camel", order: "CETARTIODACTYLA" },
  Mustela_putorius: { displayName: "Domestic Ferret", order: "CARNIVORA" },
  Pteronura_brasiliensis: { displayName: "Giant Otter", order: "CARNIVORA" },
  Cheirogaleus_medius: { displayName: "Fat Tailed Dwarf Lemur", order: "PRIMATES" },
  Desmodus_rotundus: { displayName: "Common Vampire Bat", order: "CHIROPTERA" },
  Capromys_pilorides: { displayName: "Desmarests Hutia", order: "RODENTIA" },
  Ellobius_talpinus: { displayName: "Northern Mole Vole", order: "RODENTIA" },
  Balaenoptera_acutorostrata: { displayName: "Minke Whale", order: "CETARTIODACTYLA" },
  Trichechus_manatus: { displayName: "Florida Manatee", order: "SIRENIA" },
  Panthera_onca: { displayName: "Jaguar", order: "CARNIVORA" },
  Craseonycteris_thonglongyai: { displayName: "Bumblebee Bat", order: "CHIROPTERA" },
  Cercocebus_atys: { displayName: "Sooty Mangabey", order: "PRIMATES" },
  Cryptoprocta_ferox: { displayName: "Fossa", order: "CARNIVORA" },
  Nomascus_leucogenys: { displayName: "Northern White Cheeked Gibbon", order: "PRIMATES" },
  Indri_indri: { displayName: "Indri", order: "PRIMATES" },
  Graphiurus_murinus: { displayName: "Woodland Doormouse", order: "RODENTIA" },
  Delphinapterus_leucas: { displayName: "Beluga Whale", order: "CETARTIODACTYLA" },
  Eschrichtius_robustus: { displayName: "Grey Whale", order: "CETARTIODACTYLA" },
  Bos_indicus: { displayName: "Zebu Cattle", order: "CETARTIODACTYLA" },
  Hydrochoerus_hydrochaeris: { displayName: "Capybara", order: "RODENTIA" },
  Beatragus_hunteri: { displayName: "Hirola", order: "CETARTIODACTYLA" },
  Cricetulus_griseus: { displayName: "Chinese Hamster", order: "RODENTIA" },
  Bos_taurus: { displayName: "Cattle", order: "CETARTIODACTYLA" },
  Diceros_bicornis: { displayName: "Black Rhinocerous", order: "PERISSODACTYLA" },
  Antilocapra_americana: { displayName: "Pronghorn", order: "CETARTIODACTYLA" },
  Myocastor_coypus: { displayName: "Coypu", order: "RODENTIA" },
  Felis_nigripes: { displayName: "Black Footed Cat", order: "CARNIVORA" },
  Alouatta_palliata: { displayName: "Mexican Howler Monkey", order: "PRIMATES" },
  Eptesicus_fuscus: { displayName: "Big Brown Bat", order: "CHIROPTERA" },
  Okapia_johnstoni: { displayName: "Okapi", order: "CETARTIODACTYLA" },
  Vulpes_lagopus: { displayName: "Arctic Fox", order: "CARNIVORA" },
  Psammomys_obesus: { displayName: "Fat Sand Rat", order: "RODENTIA" },
  Hystrix_cristata: { displayName: "Northern Crested Porcupine", order: "RODENTIA" },
  Ceratotherium_simum: { displayName: "Southern White Rhinoceros", order: "PERISSODACTYLA" },
  Rhinopithecus_bieti: { displayName: "Black Snub Nosed Monkey", order: "PRIMATES" },
  Erinaceus_europaeus: { displayName: "Western European Hedgehog", order: "EULIPOTYPHLA" },
  Mirounga_angustirostris: { displayName: "Northern Elephant Seal", order: "CARNIVORA" },
  Tapirus_indicus: { displayName: "Malayan Tapir", order: "PERISSODACTYLA" },
  Mandrillus_leucophaeus: { displayName: "Drill", order: "PRIMATES" },
  Cebus_capucinus: { displayName: "White Faced Sapajou", order: "PRIMATES" },
  Macaca_mulatta: { displayName: "Rhesus Monkey", order: "PRIMATES" },
  Mormoops_blainvillei: { displayName: "Ghost Faced Bat", order: "CHIROPTERA" },
  Ondatra_zibethicus: { displayName: "Muskrat", order: "RODENTIA" },
  Glis_glis: { displayName: "Edible Dormouse", order: "RODENTIA" },
  Artibeus_jamaicensis: { displayName: "Jamacian Fruit Eating Bat", order: "CHIROPTERA" },
  Cavia_aperea: { displayName: "Brazilian Guinea Pig", order: "RODENTIA" },
  Aplodontia_rufa: { displayName: "Mountain Beaver", order: "RODENTIA" },
  Mus_spretus: { displayName: "Western Wild Mouse", order: "RODENTIA" },
  Eidolon_helvum: { displayName: "Straw Colored Fruit Bat", order: "CHIROPTERA" },
  Aotus_nancymaae: { displayName: "Mas Night Monkey", order: "PRIMATES" },
  Ziphius_cavirostris: { displayName: "Cuviers Beaked Whale", order: "CETARTIODACTYLA" },
  Muscardinus_avellanarius: { displayName: "Hazel Dormouse", order: "RODENTIA" },
  Ovis_aries: { displayName: "Sheep", order: "CETARTIODACTYLA" },
  Marmota_marmota: { displayName: "Alpine Marmot", order: "RODENTIA" },
  Allactaga_bullata: { displayName: "Gobi Jerboa", order: "RODENTIA" },
  Heterocephalus_glaber: { displayName: "Naked Mole Rat", order: "RODENTIA" },
  Suricata_suricatta: { displayName: "Meerkat", order: "CARNIVORA" },
  Spilogale_gracilis: { displayName: "Western Spotted Skunk", order: "CARNIVORA" },
  Tadarida_brasiliensis: { displayName: "Mexican Free Tailed Bat", order: "CHIROPTERA" },
  Megaderma_lyra: { displayName: "Greater False Vampire Bat", order: "CHIROPTERA" },
  Platanista_gangetica: { displayName: "Indus River Dolphin", order: "CETARTIODACTYLA" },
  Orycteropus_afer: { displayName: "Aardvark", order: "TUBULIDENTATA" },
  Microgale_talazaci: { displayName: "Talazacs Shrew Tenrec", order: "AFROSORICIDA" },
  Ictidomys_tridecemlineatus: { displayName: "Thirteen Lined Ground Squirrel", order: "RODENTIA" },
  Rhinolophus_sinicus: { displayName: "Chinese Rufous Horseshoe Bat", order: "CHIROPTERA" },
  Pithecia_pithecia: { displayName: "White Faced Saki", order: "PRIMATES" },
  Petromus_typicus: { displayName: "Dassie Rat", order: "RODENTIA" },
  Cuniculus_paca: { displayName: "Lowland Paca", order: "RODENTIA" },
  Enhydra_lutris: { displayName: "Sea Otter", order: "CARNIVORA" },
  Mus_musculus: { displayName: "House Mouse", order: "RODENTIA" },
  Hipposideros_armiger: { displayName: "Great Roundleaf Bat", order: "CHIROPTERA" },
  Camelus_dromedarius: { displayName: "Arabian Camel", order: "CETARTIODACTYLA" },
  Choloepus_hoffmanni: { displayName: "Hoffmanns Two Fingered Sloth", order: "PILOSA" },
  Chaetophractus_vellerosus: { displayName: "Screaming Hairy Armadillo", order: "CINGULATA" },
  Loxodonta_africana: { displayName: "African Savanna Elephant", order: "PROBOSCIDEA" },
  Colobus_angolensis: { displayName: "Angolan Colobus", order: "PRIMATES" },
  Sorex_araneus: { displayName: "European Shrew", order: "EULIPOTYPHLA" },
  Tupaia_chinensis: { displayName: "Northern Tree Shrew", order: "SCANDENTIA" },
  Jaculus_jaculus: { displayName: "Lesser Egyptian Jerboa", order: "RODENTIA" },
  Macaca_fascicularis: { displayName: "Crab Eating Macaque", order: "PRIMATES" },
  Helogale_parvula: { displayName: "Dwarf Mongoose", order: "CARNIVORA" },
  Eulemur_flavifrons: { displayName: "Sclaters Lemur", order: "PRIMATES" },
  Microtus_ochrogaster: { displayName: "Prairie Vole", order: "RODENTIA" },
  Mus_pahari: { displayName: "Shrew Mouse", order: "RODENTIA" },
  Saguinus_imperator: { displayName: "Emperor Tamarin", order: "PRIMATES" },
  Daubentonia_madagascariensis: { displayName: "Aye Aye", order: "PRIMATES" },
  Mesocricetus_auratus: { displayName: "Golden Hamster", order: "RODENTIA" },
  Pan_paniscus: { displayName: "Pygmy Chimpanzee", order: "PRIMATES" },
  Neophocaena_asiaeorientalis: { displayName: "Yangtze Finless Porpoise", order: "CETARTIODACTYLA" },
  Rattus_norvegicus: { displayName: "Norway Rat", order: "RODENTIA" },
  Thryonomys_swinderianus: { displayName: "Greater Cane Rat", order: "RODENTIA" },
  Phocoena_phocoena: { displayName: "Harbor Porpoise", order: "CETARTIODACTYLA" },
  Nasalis_larvatus: { displayName: "Proboscis Monkey", order: "PRIMATES" },
  Tamandua_tetradactyla: { displayName: "Southern Tamandua", order: "PILOSA" },
  Rhinopithecus_roxellana: { displayName: "Golden Snub Nosed Monkey", order: "PRIMATES" },
  Chrysochloris_asiatica: { displayName: "Cape Golden Mole", order: "AFROSORICIDA" },
  Miniopterus_natalensis: { displayName: "Bats", order: "CHIROPTERA" },
  Callicebus_donacophilus: { displayName: "White Eared Titi", order: "PRIMATES" },
  Mirza_coquereli: { displayName: "Coquerels Giant Mouse Lemur", order: "PRIMATES" },
  Noctilio_leporinus: { displayName: "Greater Bulldog Bat", order: "CHIROPTERA" },
  Bubalus_bubalis: { displayName: "Water Buffalo", order: "CETARTIODACTYLA" },
  Inia_geoffrensis: { displayName: "Amazon River Dolphin", order: "CETARTIODACTYLA" },
  Xerus_inauris: { displayName: "Cape Ground Squirrel", order: "RODENTIA" },
  Tolypeutes_matacus: { displayName: "Southern Three Banded Armadillo", order: "CINGULATA" },
  Propithecus_coquereli: { displayName: "Coquerels Sifaka", order: "PRIMATES" },
  Tupaia_tana: { displayName: "Large Treeshrew", order: "SCANDENTIA" },
  Solenodon_paradoxus: { displayName: "Hispaniolan Solenodon", order: "EULIPOTYPHLA" },
  Erythrocebus_patas: { displayName: "Patas Monkey", order: "PRIMATES" },
  Eulemur_fulvus: { displayName: "Common Brown Lemur", order: "PRIMATES" },
  Orcinus_orca: { displayName: "Killer Whale", order: "CETARTIODACTYLA" },
  Zapus_hudsonius: { displayName: "Meadow Jumping Mouse", order: "RODENTIA" },
  Camelus_bactrianus: { displayName: "Bactrian Camel", order: "CETARTIODACTYLA" },
  Myotis_lucifugus: { displayName: "Little Brown Bat", order: "CHIROPTERA" },
  Mesoplodon_bidens: { displayName: "Sowerbys Beaked Whale", order: "CETARTIODACTYLA" },
  Perognathus_longimembris: { displayName: "Pacific Pocket Mouse", order: "RODENTIA" },
  Myotis_brandtii: { displayName: "Brandts Bat", order: "CHIROPTERA" },
  Chlorocebus_sabaeus: { displayName: "Green Monkey", order: "PRIMATES" },
  Chinchilla_lanigera: { displayName: "Long Tailed Chinchilla", order: "RODENTIA" },
  Canis_lupus_familiaris: { displayName: "Domestic Dog", order: "CARNIVORA" },
  Dinomys_branickii: { displayName: "Pacarana", order: "RODENTIA" },
  Pteronotus_parnellii: { displayName: "Parnells Mustached Bat", order: "CHIROPTERA" },
  Kogia_breviceps: { displayName: "Pygmy Sperm Whale", order: "CETARTIODACTYLA" },
  Ovis_canadensis: { displayName: "Peninsular Bighorn Sheep", order: "CETARTIODACTYLA" },
  Pygathrix_nemaeus: { displayName: "Red Shanked Douc", order: "PRIMATES" },
  Cricetomys_gambianus: { displayName: "Gambian Pouched Rat", order: "RODENTIA" },
  Ursus_maritimus: { displayName: "Polar Bear", order: "CARNIVORA" },
  Odocoileus_virginianus: { displayName: "White Tailed Deer", order: "CETARTIODACTYLA" },
  Macroglossus_sobrinus: { displayName: "Long Tongued Fruit Bat", order: "CHIROPTERA" },
  Lipotes_vexillifer: { displayName: "Yangtze River Dolphin", order: "CETARTIODACTYLA" },
  Cavia_tschudii: { displayName: "Montane Guinea Pig", order: "RODENTIA" },
  Saiga_tatarica: { displayName: "Russian Saiga", order: "CETARTIODACTYLA" },
  Choloepus_didactylus: { displayName: "Linnaeuss Two Toed Sloth", order: "PILOSA" },
  Equus_asinus: { displayName: "Ass", order: "PERISSODACTYLA" },
  Lycaon_pictus: { displayName: "African Hunting Dog", order: "CARNIVORA" },
  Tragulus_javanicus: { displayName: "Java Lesser Chevrotain", order: "CETARTIODACTYLA" },
  Rangifer_tarandus: { displayName: "Siberian Reindeer", order: "CETARTIODACTYLA" },
  Eubalaena_japonica: { displayName: "North Pacific Right Whale", order: "CETARTIODACTYLA" },
  Cavia_porcellus: { displayName: "Domestic Guinea Pig", order: "RODENTIA" },
  Dasyprocta_punctata: { displayName: "Central American Agouti", order: "RODENTIA" },
  Semnopithecus_entellus: { displayName: "Northern Plains Gray Langur", order: "PRIMATES" },
  Pteropus_vampyrus: { displayName: "Large Flying Fox", order: "CHIROPTERA" },
  Dasypus_novemcinctus: { displayName: "Nine Banded Armadillo", order: "CINGULATA" },
  Paradoxurus_hermaphroditus: { displayName: "Asian Palm Civet", order: "CARNIVORA" },
  Murina_feae: { displayName: "Ashy Gray Tube Nosed Bat", order: "CHIROPTERA" },
  Myotis_myotis: { displayName: "Greater Mouse Eared Bat", order: "CHIROPTERA" },
  Anoura_caudifer: { displayName: "Tailed Tailless Bat", order: "CHIROPTERA" },
  Rousettus_aegyptiacus: { displayName: "Egyptian Fruit Bat", order: "CHIROPTERA" },
  Manis_javanica: { displayName: "Malayan Pangolin", order: "PHOLIDOTA" },
  Tapirus_terrestris: { displayName: "South American Tapir", order: "PERISSODACTYLA" },
  Neomonachus_schauinslandi: { displayName: "Hawaiian Monk Seal", order: "CARNIVORA" },
  Micronycteris_hirsuta: { displayName: "Hairy Big Eared Bat", order: "CHIROPTERA" },
  Acinonyx_jubatus: { displayName: "Cheetah", order: "CARNIVORA" },
  Uropsilus_gracilis: { displayName: "Gracile Shrew Like Mole", order: "EULIPOTYPHLA" },
  Monodon_monoceros: { displayName: "Narwhal", order: "CETARTIODACTYLA" },
  Meriones_unguiculatus: { displayName: "Mongolian Jird", order: "RODENTIA" },
  Balaenoptera_bonaerensis: { displayName: "Antarctic Minke Whale", order: "CETARTIODACTYLA" },
  Otolemur_garnettii: { displayName: "Small Eared Galago", order: "PRIMATES" },
  Scalopus_aquaticus: { displayName: "Eastern Mole", order: "EULIPOTYPHLA" },
  Cercopithecus_neglectus: { displayName: "De Brazzas Monkey", order: "PRIMATES" },
  Ctenodactylus_gundi: { displayName: "Common Gundi", order: "RODENTIA" },
  Capra_hircus: { displayName: "Goat", order: "CETARTIODACTYLA" },
  Pan_troglodytes: { displayName: "Chimpanzee", order: "PRIMATES" },
  Catagonus_wagneri: { displayName: "Chacoan Peccary", order: "CETARTIODACTYLA" },
  Dipodomys_stephensi: { displayName: "Stephens Kangaroo Rat", order: "RODENTIA" },
  Carollia_perspicillata: { displayName: "Sebas Short Tailed Bat", order: "CHIROPTERA" },
  Hippopotamus_amphibius: { displayName: "Hippopotamus", order: "CETARTIODACTYLA" },
  Pteropus_alecto: { displayName: "Black Flying Fox", order: "CHIROPTERA" },
  Elaphurus_davidianus: { displayName: "Pere Davids Deer", order: "CETARTIODACTYLA" },
  Fukomys_damarensis: { displayName: "Damara Mole Rat", order: "RODENTIA" },
  Myotis_davidii: { displayName: "Bats", order: "CHIROPTERA" },
  Lasiurus_borealis: { displayName: "Eastern Red Bat", order: "CHIROPTERA" },
  Ceratotherium_simum_cottoni: { displayName: "Northern White Rhino", order: "PERISSODACTYLA" },
  Lemur_catta: { displayName: "Ring Tailed Lemur", order: "PRIMATES" },
  Odobenus_rosmarus: { displayName: "Pacific Walrus", order: "CARNIVORA" },
  Hemitragus_hylocrius: { displayName: "Nilgiri Tahr", order: "CETARTIODACTYLA" },
  Ailurus_fulgens: { displayName: "Lesser Panda", order: "CARNIVORA" },
  Mungos_mungo: { displayName: "South African Banded Mongoose", order: "CARNIVORA" },
  Elephantulus_edwardii: { displayName: "Cape Elephant Shrew", order: "MACROSCELIDEA" },
  Octodon_degus: { displayName: "Degu", order: "RODENTIA" },
  Canis_lupus: { displayName: "Domestic Dog", order: "CARNIVORA" },
  Capra_aegagrus: { displayName: "Wild Goat", order: "CETARTIODACTYLA" },
  Gorilla_gorilla: { displayName: "Western Lowland Gorilla", order: "PRIMATES" },
  Ateles_geoffroyi: { displayName: "Geoffroys Spider Monkey", order: "PRIMATES" },
  Castor_canadensis: { displayName: "North American Beaver", order: "RODENTIA" },
  Bison_bison: { displayName: "American Bison", order: "CETARTIODACTYLA" },
  Leptonychotes_weddellii: { displayName: "Weddell Seal", order: "CARNIVORA" },
  Dipodomys_ordii: { displayName: "Ords Kangaroo Rat", order: "RODENTIA" },
  Pipistrellus_pipistrellus: { displayName: "Common Pipistrelle", order: "CHIROPTERA" },
  Acomys_cahirinus: { displayName: "Cairo Spiny Mouse", order: "RODENTIA" },
  Felis_catus: { displayName: "Domestic Cat", order: "CARNIVORA" },
  Vicugna_pacos: { displayName: "Alpaca", order: "CETARTIODACTYLA" },
  Giraffa_tippelskirchi: { displayName: "Giraffe", order: "CETARTIODACTYLA" },
  Homo_sapiens: { displayName: "Human", order: "PRIMATES" },
};

export const SPECIES_ORDER_IN_API_RETURN = [
  "Acinonyx_jubatus",
  "Acomys_cahirinus",
  "Ailuropoda_melanoleuca",
  "Ailurus_fulgens",
  "Allactaga_bullata",
  "Alouatta_palliata",
  "Ammotragus_lervia",
  "Anoura_caudifer",
  "Antilocapra_americana",
  "Aotus_nancymaae",
  "Aplodontia_rufa",
  "Artibeus_jamaicensis",
  "Ateles_geoffroyi",
  "Balaenoptera_acutorostrata",
  "Balaenoptera_bonaerensis",
  "Beatragus_hunteri",
  "Bison_bison",
  "Bos_indicus",
  "Bos_mutus",
  "Bos_taurus",
  "Bubalus_bubalis",
  "Callicebus_donacophilus",
  "Callithrix_jacchus",
  "Camelus_bactrianus",
  "Camelus_dromedarius",
  "Camelus_ferus",
  "Canis_lupus",
  "Canis_lupus_familiaris",
  "Capra_aegagrus",
  "Capra_hircus",
  "Capromys_pilorides",
  "Carollia_perspicillata",
  "Castor_canadensis",
  "Catagonus_wagneri",
  "Cavia_aperea",
  "Cavia_porcellus",
  "Cavia_tschudii",
  "Cebus_albifrons",
  "Cebus_capucinus",
  "Ceratotherium_simum",
  "Ceratotherium_simum_cottoni",
  "Cercocebus_atys",
  "Cercopithecus_neglectus",
  "Chaetophractus_vellerosus",
  "Cheirogaleus_medius",
  "Chinchilla_lanigera",
  "Chlorocebus_sabaeus",
  "Choloepus_didactylus",
  "Choloepus_hoffmanni",
  "Chrysochloris_asiatica",
  "Colobus_angolensis",
  "Condylura_cristata",
  "Craseonycteris_thonglongyai",
  "Cricetomys_gambianus",
  "Cricetulus_griseus",
  "Crocidura_indochinensis",
  "Cryptoprocta_ferox",
  "Ctenodactylus_gundi",
  "Ctenomys_sociabilis",
  "Cuniculus_paca",
  "Dasyprocta_punctata",
  "Dasypus_novemcinctus",
  "Daubentonia_madagascariensis",
  "Delphinapterus_leucas",
  "Desmodus_rotundus",
  "Dicerorhinus_sumatrensis",
  "Diceros_bicornis",
  "Dinomys_branickii",
  "Dipodomys_ordii",
  "Dipodomys_stephensi",
  "Dolichotis_patagonum",
  "Echinops_telfairi",
  "Eidolon_helvum",
  "Elaphurus_davidianus",
  "Elephantulus_edwardii",
  "Ellobius_lutescens",
  "Ellobius_talpinus",
  "Enhydra_lutris",
  "Eptesicus_fuscus",
  "Equus_asinus",
  "Equus_caballus",
  "Equus_przewalskii",
  "Erinaceus_europaeus",
  "Erythrocebus_patas",
  "Eschrichtius_robustus",
  "Eubalaena_japonica",
  "Eulemur_flavifrons",
  "Eulemur_fulvus",
  "Felis_catus",
  "Felis_nigripes",
  "Fukomys_damarensis",
  "Galeopterus_variegatus",
  "Giraffa_tippelskirchi",
  "Glis_glis",
  "Gorilla_gorilla",
  "Graphiurus_murinus",
  "Helogale_parvula",
  "Hemitragus_hylocrius",
  "Heterocephalus_glaber",
  "Heterohyrax_brucei",
  "Hippopotamus_amphibius",
  "Hipposideros_armiger",
  "Hipposideros_galeritus",
  "Homo_sapiens",
  "Hyaena_hyaena",
  "Hydrochoerus_hydrochaeris",
  "Hystrix_cristata",
  "Ictidomys_tridecemlineatus",
  "Indri_indri",
  "Inia_geoffrensis",
  "Jaculus_jaculus",
  "Kogia_breviceps",
  "Lasiurus_borealis",
  "Lemur_catta",
  "Leptonychotes_weddellii",
  "Lepus_americanus",
  "Lipotes_vexillifer",
  "Loxodonta_africana",
  "Lycaon_pictus",
  "Macaca_fascicularis",
  "Macaca_mulatta",
  "Macaca_nemestrina",
  "Macroglossus_sobrinus",
  "Mandrillus_leucophaeus",
  "Manis_javanica",
  "Manis_pentadactyla",
  "Marmota_marmota",
  "Megaderma_lyra",
  "Mellivora_capensis",
  "Meriones_unguiculatus",
  "Mesocricetus_auratus",
  "Mesoplodon_bidens",
  "Microcebus_murinus",
  "Microgale_talazaci",
  "Micronycteris_hirsuta",
  "Microtus_ochrogaster",
  "Miniopterus_natalensis",
  "Miniopterus_schreibersii",
  "Mirounga_angustirostris",
  "Mirza_coquereli",
  "Monodon_monoceros",
  "Mormoops_blainvillei",
  "Moschus_moschiferus",
  "Mungos_mungo",
  "Murina_feae",
  "Mus_caroli",
  "Mus_musculus",
  "Mus_pahari",
  "Mus_spretus",
  "Muscardinus_avellanarius",
  "Mustela_putorius",
  "Myocastor_coypus",
  "Myotis_brandtii",
  "Myotis_davidii",
  "Myotis_lucifugus",
  "Myotis_myotis",
  "Myrmecophaga_tridactyla",
  "Nannospalax_galili",
  "Nasalis_larvatus",
  "Neomonachus_schauinslandi",
  "Neophocaena_asiaeorientalis",
  "Noctilio_leporinus",
  "Nomascus_leucogenys",
  "Nycticebus_coucang",
  "Ochotona_princeps",
  "Octodon_degus",
  "Odobenus_rosmarus",
  "Odocoileus_virginianus",
  "Okapia_johnstoni",
  "Ondatra_zibethicus",
  "Onychomys_torridus",
  "Orcinus_orca",
  "Orycteropus_afer",
  "Oryctolagus_cuniculus",
  "Otolemur_garnettii",
  "Ovis_aries",
  "Ovis_canadensis",
  "Pan_paniscus",
  "Pan_troglodytes",
  "Panthera_onca",
  "Panthera_pardus",
  "Panthera_tigris",
  "Pantholops_hodgsonii",
  "Papio_anubis",
  "Paradoxurus_hermaphroditus",
  "Perognathus_longimembris",
  "Peromyscus_maniculatus",
  "Petromus_typicus",
  "Phocoena_phocoena",
  "Piliocolobus_tephrosceles",
  "Pipistrellus_pipistrellus",
  "Pithecia_pithecia",
  "Platanista_gangetica",
  "Pongo_abelii",
  "Procavia_capensis",
  "Propithecus_coquereli",
  "Psammomys_obesus",
  "Pteronotus_parnellii",
  "Pteronura_brasiliensis",
  "Pteropus_alecto",
  "Pteropus_vampyrus",
  "Puma_concolor",
  "Pygathrix_nemaeus",
  "Rangifer_tarandus",
  "Rattus_norvegicus",
  "Rhinolophus_sinicus",
  "Rhinopithecus_bieti",
  "Rhinopithecus_roxellana",
  "Rousettus_aegyptiacus",
  "Saguinus_imperator",
  "Saiga_tatarica",
  "Saimiri_boliviensis",
  "Scalopus_aquaticus",
  "Semnopithecus_entellus",
  "Sigmodon_hispidus",
  "Solenodon_paradoxus",
  "Sorex_araneus",
  "Spermophilus_dauricus",
  "Spilogale_gracilis",
  "Suricata_suricatta",
  "Sus_scrofa",
  "Tadarida_brasiliensis",
  "Tamandua_tetradactyla",
  "Tapirus_indicus",
  "Tapirus_terrestris",
  "Thryonomys_swinderianus",
  "Tolypeutes_matacus",
  "Tonatia_saurophila",
  "Tragulus_javanicus",
  "Trichechus_manatus",
  "Tupaia_chinensis",
  "Tupaia_tana",
  "Tursiops_truncatus",
  "Uropsilus_gracilis",
  "Ursus_maritimus",
  "Vicugna_pacos",
  "Vulpes_lagopus",
  "Xerus_inauris",
  "Zalophus_californianus",
  "Zapus_hudsonius",
  "Ziphius_cavirostris",
];

const SPECIES_ORDER_IN_TREE = [
  "Homo_sapiens",
  "Pan_troglodytes",
  "Pan_paniscus",
  "Gorilla_gorilla",
  "Pongo_abelii",
  "Nomascus_leucogenys",
  "Colobus_angolensis",
  "Piliocolobus_tephrosceles",
  "Semnopithecus_entellus",
  "Nasalis_larvatus",
  "Pygathrix_nemaeus",
  "Rhinopithecus_roxellana",
  "Rhinopithecus_bieti",
  "Cercopithecus_neglectus",
  "Erythrocebus_patas",
  "Chlorocebus_sabaeus",
  "Papio_anubis",
  "Mandrillus_leucophaeus",
  "Cercocebus_atys",
  "Macaca_nemestrina",
  "Macaca_fascicularis",
  "Macaca_mulatta",
  "Pithecia_pithecia",
  "Callicebus_donacophilus",
  "Ateles_geoffroyi",
  "Alouatta_palliata",
  "Aotus_nancymaae",
  "Saguinus_imperator",
  "Callithrix_jacchus",
  "Saimiri_boliviensis",
  "Cebus_albifrons",
  "Cebus_capucinus",
  "Nycticebus_coucang",
  "Otolemur_garnettii",
  "Daubentonia_madagascariensis",
  "Lemur_catta",
  "Eulemur_fulvus",
  "Eulemur_flavifrons",
  "Propithecus_coquereli",
  "Indri_indri",
  "Cheirogaleus_medius",
  "Mirza_coquereli",
  "Microcebus_murinus",
  "Galeopterus_variegatus",
  "Tupaia_tana",
  "Tupaia_chinensis",
  "Ochotona_princeps",
  "Oryctolagus_cuniculus",
  "Lepus_americanus",
  "Ctenodactylus_gundi",
  "Hystrix_cristata",
  "Heterocephalus_glaber",
  "Fukomys_damarensis",
  "Thryonomys_swinderianus",
  "Petromus_typicus",
  "Chinchilla_lanigera",
  "Dinomys_branickii",
  "Octodon_degus",
  "Ctenomys_sociabilis",
  "Capromys_pilorides",
  "Myocastor_coypus",
  "Cuniculus_paca",
  "Dasyprocta_punctata",
  "Dolichotis_patagonum",
  "Hydrochoerus_hydrochaeris",
  "Cavia_aperea",
  "Cavia_tschudii",
  "Cavia_porcellus",
  "Muscardinus_avellanarius",
  "Glis_glis",
  "Graphiurus_murinus",
  "Aplodontia_rufa",
  "Xerus_inauris",
  "Spermophilus_dauricus",
  "Ictidomys_tridecemlineatus",
  "Marmota_marmota",
  "Castor_canadensis",
  "Perognathus_longimembris",
  "Dipodomys_ordii",
  "Dipodomys_stephensi",
  "Zapus_hudsonius",
  "Allactaga_bullata",
  "Jaculus_jaculus",
  "Nannospalax_galili",
  "Cricetomys_gambianus",
  "Acomys_cahirinus",
  "Psammomys_obesus",
  "Meriones_unguiculatus",
  "Rattus_norvegicus",
  "Mus_pahari",
  "Mus_caroli",
  "Mus_musculus",
  "Mus_spretus",
  "Peromyscus_maniculatus",
  "Onychomys_torridus",
  "Sigmodon_hispidus",
  "Cricetulus_griseus",
  "Mesocricetus_auratus",
  "Microtus_ochrogaster",
  "Ondatra_zibethicus",
  "Ellobius_talpinus",
  "Ellobius_lutescens",
  "Solenodon_paradoxus",
  "Erinaceus_europaeus",
  "Sorex_araneus",
  "Crocidura_indochinensis",
  "Uropsilus_gracilis",
  "Scalopus_aquaticus",
  "Condylura_cristata",
  "Megaderma_lyra",
  "Craseonycteris_thonglongyai",
  "Rhinolophus_sinicus",
  "Hipposideros_armiger",
  "Hipposideros_galeritus",
  "Macroglossus_sobrinus",
  "Eidolon_helvum",
  "Rousettus_aegyptiacus",
  "Pteropus_alecto",
  "Pteropus_vampyrus",
  "Noctilio_leporinus",
  "Mormoops_blainvillei",
  "Pteronotus_parnellii",
  "Desmodus_rotundus",
  "Tonatia_saurophila",
  "Micronycteris_hirsuta",
  "Anoura_caudifer",
  "Carollia_perspicillata",
  "Artibeus_jamaicensis",
  "Tadarida_brasiliensis",
  "Miniopterus_schreibersii",
  "Miniopterus_natalensis",
  "Lasiurus_borealis",
  "Eptesicus_fuscus",
  "Pipistrellus_pipistrellus",
  "Murina_feae",
  "Myotis_davidii",
  "Myotis_myotis",
  "Myotis_brandtii",
  "Myotis_lucifugus",
  "Equus_asinus",
  "Equus_przewalskii",
  "Equus_caballus",
  "Tapirus_indicus",
  "Tapirus_terrestris",
  "Dicerorhinus_sumatrensis",
  "Diceros_bicornis",
  "Ceratotherium_simum_cottoni",
  "Ceratotherium_simum",
  "Manis_pentadactyla",
  "Manis_javanica",
  "Paradoxurus_hermaphroditus",
  "Hyaena_hyaena",
  "Cryptoprocta_ferox",
  "Helogale_parvula",
  "Mungos_mungo",
  "Suricata_suricatta",
  "Panthera_tigris",
  "Panthera_onca",
  "Panthera_pardus",
  "Acinonyx_jubatus",
  "Puma_concolor",
  "Felis_nigripes",
  "Felis_catus",
  "Vulpes_lagopus",
  "Lycaon_pictus",
  "Canis_lupus_familiaris",
  "Canis_lupus",
  "Ursus_maritimus",
  "Ailuropoda_melanoleuca",
  "Odobenus_rosmarus",
  "Zalophus_californianus",
  "Neomonachus_schauinslandi",
  "Leptonychotes_weddellii",
  "Mirounga_angustirostris",
  "Spilogale_gracilis",
  "Ailurus_fulgens",
  "Mellivora_capensis",
  "Mustela_putorius",
  "Enhydra_lutris",
  "Pteronura_brasiliensis",
  "Vicugna_pacos",
  "Camelus_dromedarius",
  "Camelus_ferus",
  "Camelus_bactrianus",
  "Sus_scrofa",
  "Catagonus_wagneri",
  "Hippopotamus_amphibius",
  "Eubalaena_japonica",
  "Eschrichtius_robustus",
  "Balaenoptera_bonaerensis",
  "Balaenoptera_acutorostrata",
  "Kogia_breviceps",
  "Platanista_gangetica",
  "Ziphius_cavirostris",
  "Mesoplodon_bidens",
  "Lipotes_vexillifer",
  "Inia_geoffrensis",
  "Orcinus_orca",
  "Tursiops_truncatus",
  "Monodon_monoceros",
  "Delphinapterus_leucas",
  "Neophocaena_asiaeorientalis",
  "Phocoena_phocoena",
  "Tragulus_javanicus",
  "Elaphurus_davidianus",
  "Rangifer_tarandus",
  "Odocoileus_virginianus",
  "Antilocapra_americana",
  "Giraffa_tippelskirchi",
  "Okapia_johnstoni",
  "Moschus_moschiferus",
  "Bubalus_bubalis",
  "Bison_bison",
  "Bos_mutus",
  "Bos_indicus",
  "Bos_taurus",
  "Pantholops_hodgsonii",
  "Saiga_tatarica",
  "Beatragus_hunteri",
  "Ovis_canadensis",
  "Ovis_aries",
  "Ammotragus_lervia",
  "Hemitragus_hylocrius",
  "Capra_hircus",
  "Capra_aegagrus",
  "Dasypus_novemcinctus",
  "Tolypeutes_matacus",
  "Chaetophractus_vellerosus",
  "Choloepus_didactylus",
  "Choloepus_hoffmanni",
  "Myrmecophaga_tridactyla",
  "Tamandua_tetradactyla",
  "Loxodonta_africana",
  "Trichechus_manatus",
  "Procavia_capensis",
  "Heterohyrax_brucei",
  "Orycteropus_afer",
  "Elephantulus_edwardii",
  "Chrysochloris_asiatica",
  "Echinops_telfairi",
  "Microgale_talazaci",
];

// Colors generated by https://medialab.github.io/iwanthue/ with H 0-360, C 30-80, L 25-70
const ORDER_COLORS: Record<Order, string> = {
  CINGULATA: "#68003b",
  PILOSA: "#2b1924",
  PROBOSCIDEA: "#9f006d",
  SIRENIA: "#ff46c6",
  HYRACOIDEA: "#9c00b6",
  TUBULIDENTATA: "#00356c",
  MACROSCELIDEA: "#4b95fe",
  AFROSORICIDA: "#016aae",
  SCANDENTIA: "#569cc8",
  DERMOPTERA: "#006c6c",
  PRIMATES: "#114a38",
  LAGOMORPHA: "#006e22",
  RODENTIA: "#756a53",
  EULIPOTYPHLA: "#5d4500",
  CHIROPTERA: "#c68300",
  PERISSODACTYLA: "#ea6e00",
  PHOLIDOTA: "#cd5a12",
  CARNIVORA: "#b81212",
  CETARTIODACTYLA: "#97495f",
};

export const getLabel = (id: string) => {
  return SPECIES_META[id]?.displayName ?? id;
};

export const getOrder = (id: string) => {
  return SPECIES_META[id]?.order ?? null;
};

export const getColor = (id: string) => {
  const order = getOrder(id);
  const color = ORDER_COLORS[order] ?? "";
  return color;
};

type TestDataNode = { name: string; branch_length: number | null; children?: TestDataNode[] };

export const formatNode = (node: TestDataNode): TreeItem => {
  const newNode: TreeItem = { id: node.name, branch_length: node.branch_length };

  if (node.children) {
    const newChildren = node.children.map((child) => formatNode(child));
    newNode.children = newChildren;
  }

  return newNode;
};

const numberToNucleotide = new Map<number, Nucleotide>([
  [0, "-"],
  [1, "A"],
  [2, "C"],
  [3, "G"],
  [4, "T"],
]);

/**
 * Takes sequences (numbers 0-4) and a matching ordered array to map each sequence to a species,
 * and produces data for the SequenceAlignmentPlot
 */
export const makeAlignmentPlotData = (
  sequences: number[][],
  /**
   * order of species in `sequences`
   */
  speciesOrder: string[],
  /**
   * sort fn for entries in return data
   */
  sortFn: (id1: string, id2: string) => number
): { [species: string]: Nucleotide[] } => {
  if (sequences.length !== speciesOrder.length) {
    throw new Error("Number of sequences doesn't match number of species");
  }

  const mappedSequence: { [species: string]: Nucleotide[] } = {};
  sequences.forEach((sequence, i) => {
    const species = speciesOrder[i];
    mappedSequence[species] = sequence.map((num) => numberToNucleotide.get(num) ?? "-");
  });
  const sortedSequences = Object.fromEntries(Object.entries(mappedSequence).sort((a, b) => sortFn(a[0], b[0])));
  return sortedSequences;
};

export const sortSpeciesByTreeOrder = (id1: string, id2: string) =>
  SPECIES_ORDER_IN_TREE.indexOf(id1) - SPECIES_ORDER_IN_TREE.indexOf(id2);

export const phyloTreeRoot = formatNode(data241);

export const allSpecies = new Set(SPECIES_ORDER_IN_API_RETURN);
