import DownloadContentLayout from "./DownloadContentLayout";
import { Assembly } from "common/types/globalTypes";
import { allColsHidden, BiosampleTable, initialTableState } from "@weng-lab/ui-components";
import { gridVisibleRowsSelector, isAutogeneratedRow } from "@mui/x-data-grid-premium";
import { trackDownload } from "../analytics";
import { DownloadButton, DownloadButtonProps } from "./DownloadButton";
import Config from "common/config.json";

const overrideInitialTableState = {
  ...initialTableState,
  columns: {
    columnVisibilityModel: {
      ...allColsHidden,
      ontology: true,
      bedurl: true,
    },
  },
};

const classMatrix: DownloadButtonProps = {
  href: Config.Downloads.HumanCoreCollectionClassMatrix,
  label: "Core Collection Class Matrix",
  fileSize: "38.4 MB",
  bordercolor: "#0c184a",
  assembly: "GRCh38",
};

function AnnotationsBiosampleTable({ assembly }: { assembly: Assembly }) {
  return (
    <BiosampleTable
      onDownload={(url, name) => {
        trackDownload(url, name, "annotations", assembly);
      }}
      onReady={(apiRef) =>
        apiRef.current.subscribeEvent("rowExpansionChange", (_params, _event, details) => {
          const leavesAreVisible = Boolean(
            gridVisibleRowsSelector(apiRef).rows.filter((row) => !isAutogeneratedRow(row.model)).length
          );
          const currentVisibilityModel = details.api.state.columns.columnVisibilityModel;
          if (leavesAreVisible) {
            details.api.setColumnVisibilityModel({
              ...currentVisibilityModel,
              assays: true,
              collection: true,
              dnaseZ: true,
              atacZ: true,
              h3k4me3Z: true,
              h3k27acZ: true,
              ctcfZ: true,
            });
          } else {
            details.api.setColumnVisibilityModel({
              ...currentVisibilityModel,
              assays: false,
              collection: false,
              dnaseZ: false,
              atacZ: false,
              h3k4me3Z: false,
              h3k27acZ: false,
              ctcfZ: false,
            });
          }
        })
      }
      assembly={assembly}
      divHeight={{ height: 600 }}
      initialState={overrideInitialTableState}
      slotProps={{ toolbar: { csvOptions: { allColumns: true }, excelOptions: { allColumns: true } } }}
      //Temporary until we can remove default true value of this prop for all tables
      disableRowGrouping={false}
    />
  );
}

function AnnotationsByCelltype({ assembly }: { assembly: Assembly }) {
  return (
    <>
      <DownloadContentLayout title="cCREs by Cell and Tissue Type">
        <AnnotationsBiosampleTable assembly={assembly} />
      </DownloadContentLayout>
      <DownloadContentLayout title="Core Collection Class Matrix">
        <DownloadButton {...classMatrix} />
      </DownloadContentLayout>
    </>
  );
}

export default AnnotationsByCelltype;
