import Grid from "@mui/material/Grid";
import {
  Box,
  FormControl,
  FormControlLabel,
  FormLabel,
  IconButton,
  Radio,
  RadioGroup,
  Stack,
  TextField,
  Typography,
} from "@mui/material";
import { Close } from "@mui/icons-material";
import { BiosampleTable } from "@weng-lab/ui-components";
import { isAutogeneratedRow } from "@mui/x-data-grid-premium";
import { isValidAssembly } from "common/types/globalTypes";
import { CcreClassSelect } from "app/downloads/_DownloadRange/CcreClassSelect";
import { CheckboxGroup } from "app/downloads/_DownloadRange/CheckboxGroup";
import { DownloadBedButton } from "app/downloads/_DownloadRange/DownloadBedButton";
import { useDownloadRangeSelection } from "app/downloads/_DownloadRange/useDownloadRangeSelection";
import { ASSAY_OPTIONS, CONSERVATION_OPTIONS, DEFAULT_REGION } from "app/downloads/_DownloadRange/consts";

export const DownloadRange: React.FC = () => {
  const {
    assembly,
    selectAssembly,
    region,
    setRegion,
    selectedBiosample,
    selectBiosample,
    availableAssays,
    selectedAssays,
    setSelectedAssays,
    selectedConservation,
    setSelectedConservation,
    selectedClasses,
    setSelectedClasses,
    reachableClasses,
  } = useDownloadRangeSelection();

  return (
    <Grid container spacing={2}>
      <Grid size={{ xs: 12, md: 6 }}>
        <BiosampleTable
          assembly={assembly}
          disableMultipleRowSelection
          disableRowSelectionOnClick={false}
          onSelectionChange={(selected) => selectBiosample(selected[0]?.name ? selected[0] : null)}
          rowSelectionModel={{ type: "include", ids: new Set(selectedBiosample ? [selectedBiosample?.name] : []) }}
          isRowSelectable={(params) => !isAutogeneratedRow(params.row)}
          // temporary fix while other tables are not setup to group rows
          disableRowGrouping={false}
          divHeight={{ height: 600 }}
        />
      </Grid>
      <Grid size={{ xs: 12, md: 6 }}>
        <Stack spacing={1}>
          <FormControl>
            <FormLabel>Assembly</FormLabel>
            <RadioGroup
              row
              value={assembly}
              onChange={(_, value: string) => {
                if (isValidAssembly(value)) selectAssembly(value);
              }}
            >
              <FormControlLabel value="GRCh38" control={<Radio />} label="GRCh38" />
              <FormControlLabel value="mm10" control={<Radio />} label="mm10" />
            </RadioGroup>
          </FormControl>
          <Box>
            <FormLabel>Genomic Region</FormLabel>
            <TextField
              variant="outlined"
              placeholder={DEFAULT_REGION}
              value={region}
              fullWidth
              onChange={(event) => setRegion(event.target.value)}
            />
          </Box>
          <Box>
            <FormLabel>Selected Biosample</FormLabel>
            <Stack direction="row" alignItems={"center"}>
              <Typography>{`${selectedBiosample ? selectedBiosample.displayname : "N/A"}`}</Typography>
              {selectedBiosample && (
                <IconButton onClick={() => selectBiosample(null)}>
                  <Close />
                </IconButton>
              )}
            </Stack>
          </Box>
          <CcreClassSelect
            selectedClasses={selectedClasses}
            onChange={setSelectedClasses}
            reachableClasses={reachableClasses}
          />
          <CheckboxGroup
            label="Assays"
            options={ASSAY_OPTIONS}
            selected={selectedAssays}
            enabled={availableAssays}
            onChange={setSelectedAssays}
          />
          <CheckboxGroup
            label="Conservation"
            options={CONSERVATION_OPTIONS}
            selected={selectedConservation}
            onChange={setSelectedConservation}
            //Conservation scores are only available for GRCh38
            disabled={assembly === "mm10"}
          />
        </Stack>
        <DownloadBedButton
          assembly={assembly}
          region={region}
          biosampleName={selectedBiosample?.name}
          assays={selectedAssays}
          conservation={selectedConservation}
          classes={selectedClasses}
        />
      </Grid>
    </Grid>
  );
};
